[package]
name = "boss-engine-offsite-backup"
version.workspace = true
edition.workspace = true
workspace = "../../../.."

[dependencies]
anyhow = { workspace = true }
boss-engine-utils = { path = "../utils" }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
