[package]
name = "boss-ssh-transport"
version.workspace = true
edition.workspace = true
workspace = "../../../.."

[dependencies]
anyhow = { workspace = true }
boss-shell-quote = { path = "../../shell-quote" }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
