use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::app::RepobinError;

/// Lockfile recording the exact commit each pinned tool resolved to. This is
/// the repobin equivalent of flunge's hand-maintained `bin/checkleft.lock`: it
/// makes a pinned build reproducible (same tag -> same resolved commit -> same
/// binary inputs) and surfaces the resolved version so it is verifiable in
/// review. It lives next to the consuming repo's `REPOBIN.toml` and should be
/// checked in.
pub const LOCK_FILE_NAME: &str = "REPOBIN.lock";
const SUPPORTED_VERSION: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockFile {
    pub version: u32,
    #[serde(default)]
    pub tools: BTreeMap<String, LockedTool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedTool {
    /// Upstream repo URL the tool was resolved against.
    pub repo: String,
    /// The pinned tag, copied from `REPOBIN.toml` at resolve time.
    pub tag: String,
    /// The commit SHA the tag resolved to (full 40-char hex).
    pub resolved: String,
}

impl LockFile {
    pub fn empty() -> Self {
        Self {
            version: SUPPORTED_VERSION,
            tools: BTreeMap::new(),
        }
    }
}

pub fn lock_path(repo_root: &Path) -> PathBuf {
    repo_root.join(LOCK_FILE_NAME)
}

pub fn load_lock(path: &Path) -> Result<Option<LockFile>, RepobinError> {
    let raw = match std::fs::read_to_string(path) {
        Ok(value) => value,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(source) => {
            return Err(RepobinError::ReadLock {
                path: path.to_path_buf(),
                source,
            });
        }
    };
    let lock: LockFile = toml::from_str(&raw).map_err(|source| RepobinError::ParseLock {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(Some(lock))
}

pub fn write_lock(path: &Path, lock: &LockFile) -> Result<(), RepobinError> {
    let body = toml::to_string(lock).map_err(|source| RepobinError::SerializeLock {
        path: path.to_path_buf(),
        source,
    })?;
    let serialized = format!(
        "# Auto-generated by repobin. Records the exact commit each pinned tool\n\
         # resolved to. Commit this file so pinned builds stay reproducible.\n\
         {body}"
    );
    std::fs::write(path, serialized).map_err(|source| RepobinError::WriteLock {
        path: path.to_path_buf(),
        source,
    })
}

/// Record (or refresh) the resolved commit for `tool` and persist the lockfile.
/// Existing entries for other tools are preserved.
pub fn update_lock(path: &Path, tool: &str, repo: &str, tag: &str, resolved: &str) -> Result<(), RepobinError> {
    let mut lock = load_lock(path)?.unwrap_or_else(LockFile::empty);
    lock.version = SUPPORTED_VERSION;
    lock.tools.insert(
        tool.to_string(),
        LockedTool {
            repo: repo.to_string(),
            tag: tag.to_string(),
            resolved: resolved.to_string(),
        },
    );
    write_lock(path, &lock)
}

#[cfg(test)]
mod tests {
    use tempfile::TempDir;

    use super::{LOCK_FILE_NAME, load_lock, lock_path, update_lock};

    #[test]
    fn load_returns_none_when_missing() {
        let temp = TempDir::new().unwrap();
        let path = lock_path(temp.path());
        assert!(load_lock(&path).unwrap().is_none());
    }

    #[test]
    fn update_then_load_round_trips() {
        let temp = TempDir::new().unwrap();
        let path = lock_path(temp.path());
        update_lock(
            &path,
            "checkleft",
            "git@github.com:spinyfin/mono.git",
            "checkleft-v0.1.0-alpha.5",
            "4baa8fa5e7b2c1d09a3f6b8c2e1d4f7a9b5c3e8d",
        )
        .unwrap();

        let loaded = load_lock(&path).unwrap().unwrap();
        let entry = loaded.tools.get("checkleft").expect("checkleft entry");
        assert_eq!(entry.tag, "checkleft-v0.1.0-alpha.5");
        assert_eq!(entry.resolved, "4baa8fa5e7b2c1d09a3f6b8c2e1d4f7a9b5c3e8d");
        assert_eq!(entry.repo, "git@github.com:spinyfin/mono.git");

        let raw = std::fs::read_to_string(&path).unwrap();
        assert!(raw.contains("Auto-generated by repobin"), "lock should carry a header");
        assert_eq!(path.file_name().unwrap(), LOCK_FILE_NAME);
    }

    #[test]
    fn update_preserves_other_tools() {
        let temp = TempDir::new().unwrap();
        let path = lock_path(temp.path());
        update_lock(&path, "checkleft", "r1", "t1", "sha1").unwrap();
        update_lock(&path, "checks", "r2", "t2", "sha2").unwrap();

        let loaded = load_lock(&path).unwrap().unwrap();
        assert_eq!(loaded.tools.len(), 2);
        assert_eq!(loaded.tools["checkleft"].resolved, "sha1");
        assert_eq!(loaded.tools["checks"].resolved, "sha2");
    }

    #[test]
    fn update_refreshes_existing_tool() {
        let temp = TempDir::new().unwrap();
        let path = lock_path(temp.path());
        update_lock(&path, "checkleft", "r1", "t1", "sha1").unwrap();
        update_lock(&path, "checkleft", "r1", "t2", "sha2").unwrap();

        let loaded = load_lock(&path).unwrap().unwrap();
        assert_eq!(loaded.tools.len(), 1);
        assert_eq!(loaded.tools["checkleft"].tag, "t2");
        assert_eq!(loaded.tools["checkleft"].resolved, "sha2");
    }
}
