[package]
name = "boss-engine-recovery"
version.workspace = true
edition.workspace = true
workspace = "../../../.."

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
boss-log-files = { path = "../../log-files" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["process", "time"] }

[dev-dependencies]
boss-engine-test-git = { path = "../test-git" }
tempfile = { workspace = true }
