#!/bin/bash
# Generates GeneratedRealOpenerScanResult.swift by scanning the real Bazel
# `srcs` for banned "real OS opener" APIs. This runs as a Bazel action against
# the actual source files Bazel resolved — not against `#filePath` at test
# runtime — so it stays correct even though `bazel test` compiles Swift with
# `-file-prefix-pwd-is-dot`, which rewrites `#filePath` to a build-relative
# path that doesn't match the runtime cwd (see
# TestSourcesDoNotCallRealOpenerTests.swift for the runtime-side counterpart
# used by `swift test` / Xcode, where `#filePath` still works).
#
# Usage: scan_for_real_openers.sh <swift-file>...
set -euo pipefail

banned_symbols=(
  'NSWorkspace.shared.open'
  'OpenURLAction'
)

offenders=()
for f in "$@"; do
  base="$(basename "$f")"
  line_no=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line_no=$((line_no + 1))
    trimmed="${line#"${line%%[![:space:]]*}"}"
    case "$trimmed" in
      //*|\**) continue ;;
    esac
    for symbol in "${banned_symbols[@]}"; do
      if [[ "$line" == *"$symbol"* ]]; then
        offenders+=("$base:$line_no uses banned symbol \`$symbol\` — route through \`ChatViewModel.urlOpener\` (production) and a recording stub (tests).")
      fi
    done
  done < "$f"
done

echo "// Generated by scan_for_real_openers.sh from the real Bazel srcs list."
echo "// Do not edit by hand — see TestSourcesDoNotCallRealOpenerTests.swift."
echo "enum GeneratedRealOpenerScanResult {"
echo "    static let offenders: [String] = ["
for o in ${offenders[@]+"${offenders[@]}"}; do
  escaped="${o//\\/\\\\}"
  escaped="${escaped//\"/\\\"}"
  echo "        \"$escaped\","
done
echo "    ]"
echo "}"
