version = 1

[tools.buildifier]
target = "@buildifier_prebuilt//:buildifier"

[tools.boss]
target = "//tools/boss/cli:boss"

[tools.boss-event]
target = "//tools/boss/event-shim:boss-event"

[tools.bossctl]
target = "//tools/boss/bossctl:bossctl"

[tools.changelog]
target = "//tools/changelog:changelog"

[tools.checkleft]
target = "//tools/checkleft:checkleft"

[tools.checks]
target = "//tools/checkleft:checkleft"

[tools.cube]
target = "//tools/cube:cube"

[tools.hood]
target = "//tools/hood:hood"
