[package]
name = "boss-timer-wheel"
version.workspace = true
edition.workspace = true
workspace = "../../../.."

[dependencies]
boss-event-bus = { path = "../event-bus" }
tokio = { workspace = true, features = ["sync", "time", "rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "test-util"] }
