//! Reviewer worker: initial-prompt rendering and `ReviewResult` structured
//! output (design §2 and §3 of P992 "Automated reviewer pass on every
//! agent-authored PR").
//!
//! # Role
//!
//! A reviewer worker is a `pr_review` execution dispatched to the dedicated
//! review pool. It operates **read-only**: it reads the PR diff and changed
//! files, produces structured `ReviewResult` JSON, and never writes, commits,
//! pushes, or posts to GitHub. The read-only mandate is enforced at three
//! layers (design §9):
//!
//! 1. **Reviewer CLAUDE.md** — generated by
//!    [`crate::worker_setup::render_claude_md`] when `worker_kind =
//!    WorkerKind::Reviewer`; states the mandate prominently.
//! 2. **Tool denylist** — [`crate::worker_setup::reviewer_deny_rules`],
//!    wired to `WorkerKind::Reviewer` in the settings file.
//! 3. **Prompt mandate** — [`render_reviewer_initial_prompt`] repeats the
//!    read-only constraint in the task prompt alongside the review rubric.
//!
//! # Output contract
//!
//! The reviewer **writes** exactly one `ReviewResult` JSON object to the
//! engine-owned artifact path it is handed (see [`crate::structured_output`]),
//! using the `Write` tool. The completion handler reads + schema-validates
//! that file at the Stop boundary. As a **transitional fallback** (and to keep
//! remote/SSH reviewers working until the artifact is fetched cross-host), the
//! reviewer also ends its final message with the same JSON in a fenced
//! ` ```json ` block, which the legacy [`extract_review_result`] scraper reads
//! when the file is absent. The `ReviewResult` is the sole deliverable; the
//! reviewer must not emit any other action.

mod parsing;
mod render;
mod types;

pub use parsing::{classify_changed_files, extract_review_result, extract_review_result_verbose, passes_severity_gate};
pub use render::{render_reviewer_claude_md, render_reviewer_initial_prompt, render_revision_instructions};
pub use types::{
    PrReviewContext, RegressionCheck, ReviewFinding, ReviewFindingCategory, ReviewFindingConfidence,
    ReviewFindingSeverity, ReviewResult, ReviewScope,
};
