[package]
name = "boss-dispatch-reader"
version.workspace = true
edition.workspace = true
workspace = "../../../.."

[dependencies]
anyhow = { workspace = true }
bon = { workspace = true }
boss-dispatch-events = { path = "../dispatch-events" }
boss-engine-utils = { path = "../utils" }
boss-log-files = { path = "../../log-files" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
