//! Reviewer worker: initial-prompt rendering and structured output for the
//! automated reviewer pass that runs on agent-authored PRs.
//!
//! # Role
//!
//! A reviewer worker is a `pr_review` execution dispatched to the dedicated
//! review pool. It operates **read-only**: it reads the PR diff and changed
//! files, produces structured `ReviewResult` JSON, and never writes, commits,
//! pushes, or posts to GitHub. The read-only mandate is enforced at three
//! layers (design §9):
//!
//! 1. **Reviewer CLAUDE.md** — generated by the engine's `worker_setup`
//!    renderer when `worker_kind = WorkerKind::Reviewer`, which delegates to
//!    [`render_reviewer_claude_md`]; states the mandate prominently.
//! 2. **Tool denylist** — the engine's reviewer deny-rules, wired to
//!    `WorkerKind::Reviewer` in the settings file.
//! 3. **Prompt mandate** — [`render_reviewer_initial_prompt`] repeats the
//!    read-only constraint in the task prompt alongside the review rubric.
//!
//! # Output contract
//!
//! A batch reviewer writes its `ReviewerReport` JSON to an engine-owned file,
//! then submits that file through `boss propose review-report`. The engine
//! validates and accepts the proposal while the reviewer remains alive; Stop
//! completion reads proposal state rather than scraping a transcript. Legacy
//! single-reviewer executions retain `ReviewResult` until batch dispatch has
//! replaced that rollout path.
//!
//! # Crate boundary
//!
//! This crate is deliberately standalone: it renders prompt text and parses
//! reviewer output, and must never depend on `boss-engine`. The one place
//! engine-owned text flows in is [`render_reviewer_claude_md`]'s
//! `boundaries_and_coordinator` parameter, which the engine supplies from its
//! shared prompt fragments so this crate does not have to own a second copy.

mod blocks;
mod parsing;
mod render;
mod supervisor_render;
mod supervisor_types;
mod types;

pub use blocks::{render_boss_construct_sweep_block, render_supersession_flag_block};
pub use parsing::{
    PrReviewMetadata, classify_changed_files, classify_pr_review_metadata, extract_review_result,
    extract_review_result_verbose, passes_severity_gate, review_result_from_candidates,
};
pub use render::{
    ReviewOrigin, ReviewerReportDestination, render_batch_reviewer_initial_prompt, render_reviewer_claude_md,
    render_reviewer_initial_prompt, render_revision_instructions, render_revision_title,
};
pub use supervisor_render::{SupervisorReportInput, render_supervisor_claude_md, render_supervisor_initial_prompt};
pub use supervisor_types::{
    ConsolidatedFinding, ReviewerPosition, SupervisorContradiction, SupervisorSourceRole, SupervisorVerdict,
};
pub use types::{
    PrReviewContext, RegressionCheck, ReviewCoverage, ReviewFinding, ReviewFindingCategory, ReviewFindingConfidence,
    ReviewFindingSeverity, ReviewResult, ReviewScope, ReviewerReport, ReviewerReportFinding,
};
