//! Reviewer worker: initial-prompt rendering and `ReviewResult` structured
//! output for the automated reviewer pass that runs on agent-authored PRs.
//!
//! # Role
//!
//! A reviewer worker is a `pr_review` execution dispatched to the dedicated
//! review pool. It operates **read-only**: it reads the PR diff and changed
//! files, produces structured `ReviewResult` JSON, and never writes, commits,
//! pushes, or posts to GitHub. The read-only mandate is enforced at three
//! layers (design §9):
//!
//! 1. **Reviewer CLAUDE.md** — generated by the engine's `worker_setup`
//!    renderer when `worker_kind = WorkerKind::Reviewer`, which delegates to
//!    [`render_reviewer_claude_md`]; states the mandate prominently.
//! 2. **Tool denylist** — the engine's reviewer deny-rules, wired to
//!    `WorkerKind::Reviewer` in the settings file.
//! 3. **Prompt mandate** — [`render_reviewer_initial_prompt`] repeats the
//!    read-only constraint in the task prompt alongside the review rubric.
//!
//! # Output contract
//!
//! The reviewer **writes** exactly one `ReviewResult` JSON object to the
//! engine-owned artifact path it is handed, using the `Write` tool. The
//! completion handler reads + schema-validates that file at the Stop
//! boundary. As a **transitional fallback** (and to keep remote/SSH reviewers
//! working until the artifact is fetched cross-host), the reviewer also ends
//! its final message with the same JSON in a fenced ` ```json ` block, which
//! the legacy [`extract_review_result`] scraper reads when the file is
//! absent. The `ReviewResult` is the sole deliverable; the reviewer must not
//! emit any other action.
//!
//! # Crate boundary
//!
//! This crate is deliberately standalone: it renders prompt text and parses
//! reviewer output, and must never depend on `boss-engine`. The one place
//! engine-owned text flows in is [`render_reviewer_claude_md`]'s
//! `boundaries_and_coordinator` parameter, which the engine supplies from its
//! shared prompt fragments so this crate does not have to own a second copy.

mod blocks;
mod parsing;
mod render;
mod types;

pub use blocks::{render_boss_construct_sweep_block, render_supersession_flag_block};
pub use parsing::{classify_changed_files, extract_review_result, extract_review_result_verbose, passes_severity_gate};
pub use render::{render_reviewer_claude_md, render_reviewer_initial_prompt, render_revision_instructions};
pub use types::{
    PrReviewContext, RegressionCheck, ReviewFinding, ReviewFindingCategory, ReviewFindingConfidence,
    ReviewFindingSeverity, ReviewResult, ReviewScope,
};
