import Foundation

/// Resolved dependency row used by the card detail Dependencies
/// subsection. Joins the raw edge against the product's tasks /
/// chores / projects so the popover can render the prereq's title
/// and current status without re-walking the work tree.
struct WorkDependencyRow: Identifiable, Hashable {
    let id: String
    let title: String
    let status: String
    let kind: WorkDependencyKind

    enum WorkDependencyKind: String, Hashable {
        case task
        case chore
        case project
        case unknown
    }
}

/// Live runtime state for one allocated worker slot, mirroring the
/// engine's `LiveWorkerState`. Keyed by `slotId` (1..=16) — survives
/// run-record finalisation, which happens within a second of spawn.
struct WorkerLiveState: Hashable {
    let slotId: Int
    let runId: String
    let model: String
    let shellPid: Int32
    let lastEventAt: String?
    let currentTool: String?
    let lastToolEndedAt: String?
    let activity: WorkerActivity
    /// Free-text one-sentence description of what the worker is doing
    /// right now, generated by the engine's `live_status` summarizer
    /// from a tail of the transcript. `nil` while spawning, idle long
    /// enough for the prior text to have been cleared, or before the
    /// first summary lands. Rendered as the Doing-card subtitle and
    /// the Agents-tab worker header subtitle.
    let liveStatus: String?
    /// ISO-8601 timestamp of the most recent successful update to
    /// `liveStatus`. Used by the UI to dim stale values.
    let liveStatusAt: String?
    /// Set by the engine's transient-recovery sweep while this slot is
    /// being auto-resumed after a transient Claude API error (529/5xx/
    /// network), e.g. "recovering from API error (attempt 2/5)". Takes
    /// display priority over `liveStatus` — see `AgentActivityState`
    /// and the Doing-card / pane-titlebar subtitle. `nil` once the
    /// worker's next hook event proves it resumed, or once the slot is
    /// released.
    let recoveryStatus: String?
}

enum WorkerActivity: String, Hashable {
    case spawning
    case working
    case waitingForInput = "waiting_for_input"
    case idle
    case errored
    case terminated

    /// Short human-readable label suitable for the pane titlebar pill.
    /// We pair this with the model name (e.g., "claude-opus-4-7") so
    /// the user sees both `Claude Opus 4.7 · Working` rather than
    /// the legacy "Claude Unknown".
    var label: String {
        switch self {
        case .spawning: "Spawning"
        case .working: "Working"
        case .waitingForInput: "Waiting"
        case .idle: "Idle"
        case .errored: "Errored"
        case .terminated: "Terminated"
        }
    }
}

enum AgentActivityState {
    case active
    case waiting(reason: String)
    case errored(reason: String)
    case none
    /// The row is `status=todo, autostart=true` and no worker slot is
    /// free yet. The engine has committed to dispatching it; the pool
    /// is just full. Renders as a hourglass rather than a coloured dot
    /// so it reads as "queued" rather than "active or paused worker".
    case dispatchPending

    /// Build from the persisted task runtime status alone. Used as
    /// the fallback when no LiveWorkerState is available (worker
    /// hasn't emitted any hook events yet, or run is no longer
    /// active).
    init(runtime: WorkTaskRuntime?) {
        guard let runtime, let executionStatus = runtime.executionStatus else {
            self = .none
            return
        }
        switch executionStatus {
        case "running":
            if runtime.runStatus == "active" {
                self = .active
            } else {
                self = .waiting(reason: "Run \(runtime.runStatus ?? "in progress")")
            }
        case "ready":
            self = .waiting(reason: "Queued for a worker")
        case "waiting_human":
            self = .waiting(reason: "Waiting on human input")
        case "waiting_review":
            self = .waiting(reason: "Waiting on review")
        case "waiting_merge":
            self = .waiting(reason: "Waiting on merge")
        case "waiting_dependency":
            self = .waiting(reason: "Waiting on dependency")
        case "failed":
            self = .waiting(reason: "Last run failed")
        case "completed":
            self = .none
        default:
            self = .waiting(reason: executionStatus.replacingOccurrences(of: "_", with: " "))
        }
    }

    /// Build by preferring engine-supplied LiveWorkerState (sourced
    /// from hook events) when available, falling back to the
    /// persisted task runtime status. The dot color now distinguishes
    /// working / waiting-on-input / idle / errored rather than always
    /// rendering the same yellow `running` indicator.
    init(runtime: WorkTaskRuntime?, liveState: WorkerLiveState?) {
        if let liveState {
            switch liveState.activity {
            case .working:
                self = .active
            case .waitingForInput:
                self = .waiting(reason: "Waiting on user input")
            case .idle:
                if let recovering = liveState.recoveryStatus, !recovering.isEmpty {
                    self = .waiting(reason: recovering)
                } else {
                    self = .waiting(reason: "Worker idle between turns")
                }
            case .spawning:
                self = .waiting(reason: "Worker spawning")
            case .errored:
                self = .errored(reason: "Worker reported an error")
            case .terminated:
                self = .none
            }
            return
        }
        self.init(runtime: runtime)
    }

    /// Resolve the activity state for a card in the Doing lane.
    ///
    /// Centralises the precedence rules that previously lived inline in
    /// `WorkBoardCardItem` so they are unit-testable without hosting the
    /// SwiftUI card.
    ///
    /// Precedence:
    /// 1. Dispatch-pending (status=todo, autostart, no slot free yet)
    ///    wins outright — the engine intends to run it but hasn't.
    /// 2. A worker paused on a permission prompt
    ///    (`activity == .waitingForInput`) reads as *waiting*, not
    ///    active. Without this, the card shows a green "working" dot
    ///    while the run is actually stalled on an input prompt no one
    ///    is watching for. This must precede the bound-slot shortcut
    ///    below; it clears on its own once the worker resumes and the
    ///    activity flips back to `.working`.
    /// 3. A bound live worker otherwise reads as active.
    /// 4. Conflict / CI-remediation runs without a bound live worker
    ///    read as their respective "resolving" waits.
    /// 5. Fall back to the runtime+liveState mapping.
    static func forDoingCard(
        runtime: WorkTaskRuntime?,
        liveState: WorkerLiveState?,
        isDispatchPending: Bool,
        isResolvingConflicts: Bool,
        isRemediatingCI: Bool,
        isAIReviewing: Bool = false
    ) -> AgentActivityState {
        if isDispatchPending {
            return .dispatchPending
        }
        if liveState?.activity == .waitingForInput {
            return .waiting(reason: "Waiting on user input")
        }
        if liveState?.slotId != nil {
            return .active
        }
        if isResolvingConflicts {
            return .waiting(reason: "Resolving merge conflict")
        }
        if isRemediatingCI {
            return .waiting(reason: "Resolving CI failure")
        }
        if isAIReviewing {
            return .waiting(reason: "AI review in progress")
        }
        return AgentActivityState(runtime: runtime, liveState: liveState)
    }

    var tooltip: String {
        switch self {
        case .active:
            return "Agent is actively working"
        case .waiting(let reason):
            return reason
        case .errored(let reason):
            return reason
        case .none:
            return "No agent attached"
        case .dispatchPending:
            return "Queued — waiting for a worker slot"
        }
    }
}

/// Swift mirror of `boss_protocol::ConflictResolution`. One engine
/// attempt to clear a merge conflict on an `in_review` PR. Powers the
/// Engine tab's attempt-row list (design Phase 5 #14) and the
/// "🔧 conflict cleared" PR-card badge (#15).
struct WorkConflictResolution: Identifiable, Hashable {
    let id: String
    var productID: String
    var workItemID: String
    var prURL: String
    var prNumber: Int
    var headBranch: String
    var baseBranch: String
    var baseSHAAtTrigger: String?
    var headSHABefore: String?
    var headSHAAfter: String?
    /// `pending` / `running` / `succeeded` / `failed` / `abandoned` /
    /// `superseded`. See the wire-type docs in `boss_protocol::types`
    /// for the lifecycle.
    var status: String
    var failureReason: String?
    var cubeLeaseID: String?
    var cubeWorkspaceID: String?
    var workerID: String?
    /// Raw JSON blob the worker prompt was built from. Carried verbatim
    /// here so the detail panel can surface it without a separate fetch.
    var conflictDiagnosis: String?
    var createdAt: String
    var startedAt: String?
    var finishedAt: String?
    /// Soft FK to the `tasks.id` of the revision task spawned by this attempt.
    /// `nil` for pre-unification rows and attempts retired before a revision was created.
    var revisionTaskId: String? = nil
}

/// PR-card chip state for the CI auto-fix flow (design Q11 / Phase
/// 11 #37). Either "engine is still trying" (with a numeric
/// `used/budget`) or "engine has given up." The exhausted variant
/// stays visible until the user kicks `boss engine ci retry`; the
/// in-flight variant clears when the next probe observes CI back at
/// `Clean`.
struct CiFailureBadge: Equatable, Hashable {
    enum State: String, Hashable {
        /// `blocked: ci_failure` — engine still trying.
        case inFlight = "in_flight"
        /// `blocked: ci_failure_exhausted` — engine has given up.
        case exhausted
    }
    var state: State
    var attemptsUsed: Int
    var budget: Int
}

/// Swift mirror of `boss_protocol::CiRemediation`. One engine attempt
/// to clear a CI failure on an `in_review` PR. Powers the Engine
/// tab's CI rows (design Phase 11 #37) and the per-PR badges (Q11).
struct WorkCiRemediation: Identifiable, Hashable {
    let id: String
    var productID: String
    var workItemID: String
    var prURL: String
    var prNumber: Int
    var headBranch: String
    var headSHAAtTrigger: String
    var headSHAAfter: String?
    /// `"fix"` or `"retrigger"` — the engine's pre-spawn triage call.
    var attemptKind: String
    /// `1` for fix-kind attempts that actually pushed; `0` for
    /// retriggers and triage-bailouts.
    var consumesBudget: Int
    /// JSON-encoded list of failing-check snapshots captured at trigger
    /// time. Stored as a verbatim string; consumers parse on demand.
    var failedChecks: String
    /// Worker-assigned classification of the failure after reading the
    /// log — one of `tractable` / `flaky_or_infra` / `unfixable`. `nil`
    /// until the worker fills it.
    var triageClass: String?
    var logExcerpt: String?
    /// `pending` / `running` / `succeeded` / `failed` / `abandoned` /
    /// `superseded`. See the wire-type docs in `boss_protocol::types`.
    var status: String
    var failureReason: String?
    var cubeLeaseID: String?
    var cubeWorkspaceID: String?
    var workerID: String?
    var createdAt: String
    var startedAt: String?
    var finishedAt: String?
    /// Soft FK to the `tasks.id` of the revision task spawned by this attempt.
    /// `nil` for pre-unification rows, retrigger attempts, and attempts retired
    /// before a revision was created.
    var revisionTaskId: String? = nil
}
