pub use boss_transcript_markdown as transcript_markdown;

pub mod answer_agent;
pub mod app;
pub mod attentions_detector;
pub mod audit;
pub mod audit_effort;
pub use boss_engine_automation_schedule as automation_schedule;
pub mod automation_scheduler;
pub mod automation_triage;
pub mod blocking_signal;
pub mod boss_construct_scan;
pub mod build_info;
pub mod build_wait;
pub mod build_wait_tracker;
pub use boss_ci_log_reader as ci_log_reader;
pub mod ci_watch;
pub use boss_claude_client as claude_client;
pub mod cli;
pub mod comment_classifier;
pub mod comments_anchor;
pub mod completion;
pub mod config;
pub use boss_conflict_diagnosis as conflict_diagnosis;
pub mod conflict_ladder;
pub mod conflict_watch;
pub mod coordinator;
pub mod cube_commands;
pub mod cube_lease_heartbeat;
pub mod database_backup;
pub mod dead_pane_sweep;
pub mod dead_pid_sweep;
pub mod deferred_scope;
pub mod dep_unblock_sweep;
pub mod design_detector;
pub use boss_deterministic_resolvers as deterministic_resolvers;
pub mod dispatch_events;
pub mod dispatch_failure_recovery_sweep;
pub(crate) mod dispatch_spillover;
pub mod doc_fetcher;
pub use boss_editorial as editorial;
pub use boss_engine_driver as driver;
pub mod dispatch_reader;
pub mod editorial_hook;
pub use boss_engine_effort as effort;
pub mod engine_control;
pub mod envelope_watch;
pub mod events_socket;
pub mod execution_liveness;
pub mod execution_retention_sweep;
pub mod external_tracker;
pub use boss_feature_flags as feature_flags;
pub mod host_adapter;
pub mod host_reconcile;
pub mod host_registry;
pub mod host_scheduling;
pub mod husk_pane_sweep;
pub mod ipc_log;
pub mod live_status;
pub mod live_status_loop;
pub mod live_worker_state;
pub mod lost_workspace_sweep;
pub mod materializer;
pub mod merge_parent_deletion;
pub mod merge_poller;
pub mod merge_when_ready;
// The metrics framework lives in its own crate; alias it under the
// module path the engine has always used it by. `metrics_init` holds
// the engine-specific startup registration that can't move down
// (it names every engine module that declares a handle), and
// `metrics_store` backs the framework's storage trait with `WorkDb`.
pub use boss_metrics as metrics;
// Re-exported so the declaration macros keep resolving as
// `crate::register_counter!` at every engine call site; the macros
// are `#[macro_export]`ed from `boss_engine_metrics_registry` and
// re-exported through `boss_metrics`.
pub use boss_metrics::{register_counter, register_gauge};
pub mod metrics_init;
pub mod metrics_store;
pub mod no_op_signal;
pub mod nudge_breaker;
pub mod orphan_sweep;
pub mod pane_summary;
pub mod planner;
pub mod pool_claim_sweep;
pub mod population_timing;
pub mod populator;
pub use boss_pr_template as pr_template;
pub mod pr_review;
pub mod pr_review_recovery;
pub mod pr_url_capture;
pub(crate) mod prompt_fragments;
pub mod protocol;
pub(crate) mod reconcile_audit;
pub mod recovery_backup;
pub mod remote_lease_reconcile;
pub mod remote_reattach;
pub mod remote_transcript;
pub mod remote_wrapper;
pub mod repo_slug;
pub mod resolution_signal_capture;
pub mod run_reconcile;
pub mod runner;
pub mod settings;
pub mod spawn_ack_sweep;
pub mod spawn_flow;
pub mod spawn_health;
pub mod speculative_conflict;
pub mod ssh_spawn;
pub use boss_ssh_transport as ssh_transport;
pub mod stacked_pr_structuring;
pub mod stale_worker_sweep;
pub mod structured_output;
pub mod supersession_scan;
pub(crate) mod sweep_loop;
pub mod syspolicyd_monitor;
pub mod terminal_work_sweep;
#[cfg(test)]
pub(crate) mod test_support;
pub use boss_transcript_tail as transcript_tail;
pub mod trace_rotation;
pub use boss_engine_transient_error as transient_error;
pub mod transient_recovery;
pub mod work;
pub mod work_dependencies;
pub mod worker_escalation;
pub mod worker_registry;
pub mod worker_sandbox_audit;
pub mod worker_setup;
pub mod wrapper_distribution;
