use super::*;

use std::time::Instant;

use crate::population_timing::{PopulationTrace, elapsed_ms, segment};

/// Truncate `s` to at most `max_chars` characters (char-boundary-safe —
/// `s.len()` counts bytes, which would panic mid-codepoint on non-ASCII
/// input), appending `…` when it was cut. Used to keep a `deferred_scope`
/// marker's freeform `summary=` text from producing an unreasonably long
/// task title.
fn truncate_chars(s: &str, max_chars: usize) -> String {
    if s.chars().count() <= max_chars {
        return s.to_owned();
    }
    let mut truncated: String = s.chars().take(max_chars).collect();
    truncated.push('…');
    truncated
}

/// Whether `WorkDb::list_tasks` — the general task-listing surface behind
/// `boss task list` and the frontend's `ListTasks` RPC — includes `kind` in
/// its result set. Exhaustive match: adding a new [`TaskKind`] variant is a
/// compile error here until this function says whether the new kind
/// belongs in `list_tasks`'s result, instead of a hand-maintained SQL
/// string list silently missing it (see incident
/// postmortem-archived-fanout-2026-07-20, where `design_postmortem` and
/// `followup` were invisible on every listing surface because of exactly
/// that).
///
/// A kind is excluded only when it has a compensating listing surface of
/// its own (`Chore` → `list_chores`) or is deliberately non-listed by
/// design (`Revision` → rolls up onto its parent's card, never a
/// standalone row — see `project_postmortem_sweep.rs`'s "rule 2" and the
/// kanban design doc). Every other kind belongs here by default.
fn kind_returned_by_list_tasks(kind: &TaskKind) -> bool {
    match kind {
        TaskKind::Chore => false,
        TaskKind::Revision => false,
        TaskKind::Design
        | TaskKind::Followup
        | TaskKind::Investigation
        | TaskKind::DesignPostmortem
        | TaskKind::ProjectTask
        | TaskKind::Task => true,
    }
}

/// `... IN (...)` fragment for [`WorkDb::list_tasks`]'s kind filter,
/// generated from [`kind_returned_by_list_tasks`] rather than hand-
/// maintained as a literal SQL string. Iterates [`TaskKind::ALL`], which is
/// generated by the `task_kind_variants!` macro invocation in `task.rs`
/// from the same list that drives `TaskKind::as_str`/`from_str` — the
/// compiler forces that invocation to cover every enum variant (a missing
/// variant is a non-exhaustive-match compile error), so `ALL` cannot omit a
/// `TaskKind` variant (see incident postmortem-archived-fanout-2026-07-20
/// for the original invisible-kind failure this exists to prevent). Built
/// from a fixed, compile-time-known set of `TaskKind` variants (never user
/// input), so formatting it directly into the query string is safe.
fn list_tasks_kind_filter_sql() -> String {
    TaskKind::ALL
        .iter()
        .filter(|kind| kind_returned_by_list_tasks(kind))
        .map(|kind| format!("'{}'", kind.as_str()))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The write half of [`WorkDb::create_attention_item`], factored out to a
/// bare `conn: &Connection` so it can be driven either by that method's own
/// short-lived transaction, or by another caller that already holds an open
/// transaction of its own — e.g. [`crate::work::proposal_apply`], which
/// stamps a `worker_proposals` row and its produced attention item
/// atomically in one transaction (`Transaction` derefs to `Connection`, so
/// passing `&tx` here just works).
pub(crate) fn insert_attention_item_row(
    conn: &Connection,
    input: &CreateAttentionItemInput,
) -> Result<WorkAttentionItem> {
    let (execution_id, work_item_id) = attention_target_from_input(conn, input)?;

    let id = next_id("attn");
    let now = now_string();
    let status = input.status.clone().unwrap_or_else(|| "open".to_owned());
    let resolved_at = normalize_optional_text(input.resolved_at.clone());

    conn.execute(
        "INSERT INTO work_attention_items (
            id, execution_id, work_item_id, kind, status, title, body_markdown, created_at, resolved_at
         ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
        params![
            id,
            execution_id,
            work_item_id,
            input.kind,
            status,
            input.title,
            input.body_markdown,
            now,
            resolved_at,
        ],
    )?;

    query_attention_item(conn, &id)?.with_context(|| format!("missing attention item after insert: {id}"))
}

impl WorkDb {
    pub fn create_attention_item(&self, input: CreateAttentionItemInput) -> Result<WorkAttentionItem> {
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        let item = insert_attention_item_row(&tx, &input)?;
        tx.commit()?;
        Ok(item)
    }

    pub fn list_attention_items(&self, execution_id: &str) -> Result<Vec<WorkAttentionItem>> {
        let conn = self.connect()?;
        ensure_execution_exists(&conn, execution_id)?;

        let mut stmt = conn.prepare(
            "SELECT id, execution_id, work_item_id, kind, status, title, body_markdown, created_at, resolved_at, converted_task_id
             FROM work_attention_items
             WHERE execution_id = ?1
             ORDER BY created_at ASC, id ASC",
        )?;
        let rows = stmt.query_map([execution_id], map_attention_item)?;
        collect_rows(rows)
    }

    /// List the sticky, pre-dispatch attention items attached to a
    /// work item (i.e. `work_item_id IS NOT NULL`). Used by the
    /// `repo_unresolved` surface and any future work-item-scoped
    /// attention flows. Errors if the work item id is unknown so
    /// callers can't accidentally silently no-op on a typo. Deliberately
    /// permissive of tombstoned tasks (e.g. an archived-and-tombstoned
    /// moot revision) so the `revision_archived` attention item raised at
    /// archival time stays reachable afterwards.
    pub fn list_attention_items_for_work_item(&self, work_item_id: &str) -> Result<Vec<WorkAttentionItem>> {
        let conn = self.connect()?;
        let _ = product_id_for_work_item_including_deleted(&conn, work_item_id)?;
        let mut stmt = conn.prepare(
            "SELECT id, execution_id, work_item_id, kind, status, title, body_markdown, created_at, resolved_at, converted_task_id
             FROM work_attention_items
             WHERE work_item_id = ?1
             ORDER BY created_at ASC, id ASC",
        )?;
        let rows = stmt.query_map([work_item_id], map_attention_item)?;
        collect_rows(rows)
    }

    pub fn get_attention_item(&self, id: &str) -> Result<WorkAttentionItem> {
        let conn = self.connect()?;
        query_attention_item(&conn, id).require("attention item", id)
    }

    /// Create an external-tracker attention item for `work_item_id` unless one
    /// with the same `kind` is already open. Idempotent: repeated reconciler
    /// ticks for the same failure do not pile up rows.
    pub fn upsert_external_tracker_attention(
        &self,
        work_item_id: &str,
        kind: &str,
        title: &str,
        body_markdown: &str,
    ) -> Result<()> {
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        let _ = product_id_for_work_item(&tx, work_item_id)?;
        let already_open: i64 = tx.query_row(
            "SELECT EXISTS(
                 SELECT 1 FROM work_attention_items
                 WHERE work_item_id = ?1
                   AND kind = ?2
                   AND status = 'open'
             )",
            params![work_item_id, kind],
            |row| row.get(0),
        )?;
        if already_open == 0 {
            let id = next_id("attn");
            let now = now_string();
            tx.execute(
                "INSERT INTO work_attention_items (
                    id, execution_id, work_item_id, kind, status, title, body_markdown, created_at, resolved_at
                 ) VALUES (?1, NULL, ?2, ?3, 'open', ?4, ?5, ?6, NULL)",
                params![id, work_item_id, kind, title, body_markdown, now],
            )?;
        } else {
            // Refresh the existing open item's title/body rather than
            // leaving it frozen at whatever it said the first time it
            // tripped — a caller like the churn guard re-files on every
            // sweep pass with an updated failure count / execution list,
            // and a stale snapshot misleads the operator into thinking
            // nothing has changed since the first trip.
            tx.execute(
                "UPDATE work_attention_items
                    SET title = ?3, body_markdown = ?4
                  WHERE work_item_id = ?1
                    AND kind = ?2
                    AND status = 'open'",
                params![work_item_id, kind, title, body_markdown],
            )?;
        }
        tx.commit()?;
        Ok(())
    }

    /// Mark all open attention items of `kind` for `work_item_id` as resolved.
    /// A no-op when none are open. Used by the external-tracker reconciler to
    /// clear stale failure items once a product recovers.
    pub fn resolve_external_tracker_attention(&self, work_item_id: &str, kind: &str) -> Result<()> {
        let conn = self.connect()?;
        resolve_attention_kind_in_tx(&conn, work_item_id, kind)?;
        Ok(())
    }

    /// File (idempotently) the operator-visible attention item raised when
    /// [`crate::orphan_sweep`] or [`crate::pr_review_recovery`] trips the
    /// shared churn guard and parks a work item instead of auto-redispatching
    /// it — see [`crate::work::CHURN_GUARD_PARKED_ATTENTION_KIND`]. Reuses
    /// [`Self::upsert_external_tracker_attention`] so repeated trips across
    /// sweep passes (every ~60s) don't pile up duplicate rows: the item stays
    /// open until [`request_execution_in_tx_with_live_check`] resolves it on
    /// the work item's next dispatch attempt.
    ///
    /// Best-effort: the caller has already logged the trip via
    /// `tracing::warn!`; a failure here is logged and swallowed rather than
    /// aborting the sweep pass.
    pub fn file_churn_guard_parked_attention(
        &self,
        work_item_id: &str,
        source: &str,
        recent_terminal: i64,
        failing_execution_ids: &[String],
    ) {
        let title = format!("Parked by churn guard — {recent_terminal} recent failures");
        let ids = if failing_execution_ids.is_empty() {
            "(could not resolve the failing execution ids)".to_owned()
        } else {
            failing_execution_ids.join(", ")
        };
        let window_hours = ORPHAN_REDISPATCH_CHURN_GUARD_WINDOW_SECS / 3600;
        let body = format!(
            "The `{source}` sweep stopped auto-redispatching this work item: it produced \
             {recent_terminal} terminal executions within the trailing {window_hours}h window \
             (threshold {ORPHAN_REDISPATCH_CHURN_GUARD_THRESHOLD}), which usually means something \
             structural is broken (a bad host, a repo/config issue) rather than a one-off blip.\n\n\
             Failing executions: {ids}\n\n\
             This clears automatically once the window drains below the threshold and the next \
             sweep pass redispatches successfully. To bypass the guard and retry immediately, run \
             `bossctl work start {work_item_id}`."
        );
        if let Err(err) =
            self.upsert_external_tracker_attention(work_item_id, CHURN_GUARD_PARKED_ATTENTION_KIND, &title, &body)
        {
            tracing::warn!(
                work_item_id = %work_item_id,
                ?err,
                "churn guard: failed to file parked attention item",
            );
        }
    }

    /// File (idempotently) the operator-visible attention item raised when
    /// [`crate::dispatch_stall_escalation`] finds a dispatch timeline stuck
    /// in one stage past
    /// [`crate::dispatch_stall_escalation::PERSISTENT_STALL_THRESHOLD`] —
    /// see [`crate::work::DISPATCH_STAGE_STALLED_ATTENTION_KIND`]. Reuses
    /// [`Self::upsert_external_tracker_attention`] so repeated sweep ticks
    /// refresh the same row's elapsed-time text instead of piling up
    /// duplicates; the item stays open until the execution finally claims a
    /// worker slot (`Coordinator::dispatch_claimed_execution` resolves it).
    ///
    /// Best-effort: a failure here is logged and swallowed by the caller
    /// rather than aborting the sweep pass.
    pub fn file_dispatch_stage_stalled_attention(
        &self,
        work_item_id: &str,
        execution_id: &str,
        stalled_stage: &str,
        elapsed_secs: u64,
        threshold_secs: u64,
    ) -> Result<()> {
        let elapsed_minutes = elapsed_secs / 60;
        let title = format!("Dispatch stuck at `{stalled_stage}` for {elapsed_minutes}m");
        let body = format!(
            "Execution `{execution_id}` has been in dispatch stage `{stalled_stage}` for {elapsed_secs}s \
             without progressing — past the persistent-stall threshold ({threshold_secs}s).\n\n\
             This clears automatically once the execution claims a worker slot. See `bossctl dispatch \
             diagnose {execution_id}` for the full timeline, or `bossctl dispatch ghost-active \
             --include-stalled` for every currently-stuck execution."
        );
        self.upsert_external_tracker_attention(work_item_id, DISPATCH_STAGE_STALLED_ATTENTION_KIND, &title, &body)
    }

    /// Decide whether a persistently-stalled execution the dispatch-stall
    /// escalation sweep detected should be escalated onto the work-item
    /// attention surface — the terminal/liveness/id-kind gate the file-scan
    /// detector ([`crate::dispatch_reader::persistently_stalled`])
    /// deliberately cannot apply (it is DB-free so it works when the engine
    /// RPC is wedged). Consults the execution's authoritative `work_item_id`
    /// and `status` from `work_executions` rather than trusting the mirror
    /// line, and returns a [`StallEscalation`] the sweep tallies and acts on.
    ///
    /// Only [`StallEscalation::Escalate`] should be filed via
    /// [`Self::file_dispatch_stage_stalled_attention`]. The other variants —
    /// a terminal/dead timeline, a mirror with no surviving row, or an
    /// automation-triage execution whose `auto_…` id has no kanban card —
    /// are the classes that used to make the sweep re-file (and warn) every
    /// pass forever. See [`StallEscalation`] for the full rationale.
    pub fn classify_dispatch_stall(&self, execution_id: &str) -> Result<StallEscalation> {
        let conn = self.connect()?;
        let Some(execution) = query_execution(&conn, execution_id)? else {
            return Ok(StallEscalation::Missing);
        };
        if execution.status.is_terminal() {
            return Ok(StallEscalation::Terminal);
        }
        // `classify_id` accepts only product/project/task ids — the exact set
        // `file_dispatch_stage_stalled_attention` can target. An automation
        // (`auto_…`) or other non-work-item id falls through here.
        if classify_id(&execution.work_item_id).is_err() {
            return Ok(StallEscalation::NotWorkItem);
        }
        Ok(StallEscalation::Escalate {
            work_item_id: execution.work_item_id,
        })
    }

    /// Mark every open `worker_escalation` / `worker_blocked` attention item
    /// for `execution_id` as resolved. Returns the count resolved (`0` when
    /// none were open — a normal, non-error case).
    ///
    /// Called when the coordinator explicitly probes the worker
    /// (`bossctl probe` / `FrontendRequest::ProbeRun`) — issuing a probe IS
    /// the coordinator's documented ack gesture for both markers (e.g.
    /// `[effort-escalation-ack] … next_dispatch=true`), so resolving here
    /// resumes [`crate::completion::WorkerCompletionHandler`]'s suppressed
    /// "produce a PR" auto-nudge on the run's next Stop without a separate
    /// resolve RPC. See `crate::worker_escalation` for the marker contract.
    pub fn resolve_worker_signal_attentions_for_execution(&self, execution_id: &str) -> Result<usize> {
        let conn = self.connect()?;
        let now = now_string();
        let rows = conn.execute(
            "UPDATE work_attention_items
             SET status = 'resolved', resolved_at = ?1
             WHERE execution_id = ?2
               AND kind IN (?3, ?4)
               AND status = 'open'",
            params![
                now,
                execution_id,
                crate::worker_escalation::WORKER_ESCALATION_ATTENTION_KIND,
                crate::worker_escalation::WORKER_BLOCKED_ATTENTION_KIND,
            ],
        )?;
        Ok(rows)
    }

    /// Close an open `deferred_scope` attention item without producing a
    /// followup task — the human's conscious call that the deferred
    /// remainder needs no further tracking. Rejects any other kind (the
    /// closure verb `worker_escalation`/`worker_blocked` already have via
    /// [`Self::resolve_worker_signal_attentions_for_execution`] doesn't
    /// apply here) and any non-`open` item (no double-closing).
    pub fn resolve_deferred_scope_attention(&self, id: &str) -> Result<WorkAttentionItem> {
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        let attention = query_attention_item(&tx, id)?.with_context(|| format!("unknown attention item: {id}"))?;
        if attention.kind != crate::deferred_scope::DEFERRED_SCOPE_ATTENTION_KIND {
            bail!(
                "attention item {id} is not a deferred_scope item (kind = {})",
                attention.kind
            );
        }
        if attention.status != "open" {
            bail!("attention item {id} is not open (status = {})", attention.status);
        }
        let now = now_string();
        tx.execute(
            "UPDATE work_attention_items SET status = 'accepted', resolved_at = ?2 WHERE id = ?1",
            params![id, now],
        )?;
        let updated =
            query_attention_item(&tx, id)?.with_context(|| format!("missing attention item after update: {id}"))?;
        tx.commit()?;
        Ok(updated)
    }

    /// File a followup task from an open `deferred_scope` attention item
    /// (the "Create task" gesture) and atomically flip the item to
    /// `status = "converted"` with `converted_task_id` set to the new
    /// task. The new task's name/description are prefilled from the
    /// marker's `summary`/`reason` fields plus provenance to the source
    /// task and (when it has one) its PR — mirroring the
    /// `TaskKind::Followup` / `origin_task_short_id` / `origin_pr_number`
    /// convention `action_attention_group`'s followup-group path already
    /// uses for PR-review findings.
    pub fn create_task_from_deferred_scope_attention(&self, attention_id: &str) -> Result<(WorkAttentionItem, Task)> {
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;

        let attention = query_attention_item(&tx, attention_id)?
            .with_context(|| format!("unknown attention item: {attention_id}"))?;
        if attention.kind != crate::deferred_scope::DEFERRED_SCOPE_ATTENTION_KIND {
            bail!(
                "attention item {attention_id} is not a deferred_scope item (kind = {})",
                attention.kind
            );
        }
        if attention.status != "open" {
            bail!(
                "attention item {attention_id} is not open (status = {})",
                attention.status
            );
        }
        let execution_id = attention
            .execution_id
            .as_deref()
            .with_context(|| format!("deferred_scope attention item {attention_id} has no execution_id"))?;
        let execution =
            query_execution(&tx, execution_id)?.with_context(|| format!("unknown execution: {execution_id}"))?;
        let source_task = query_task(&tx, &execution.work_item_id)?
            .with_context(|| format!("unknown source work item: {}", execution.work_item_id))?;

        // The marker line lives verbatim inside `body_markdown`'s fenced
        // code block; re-run the same detector that filed it rather than
        // re-implementing fenced-block extraction.
        let marker_line = crate::deferred_scope::detect_deferred_scope_items(&attention.body_markdown)
            .into_iter()
            .next()
            .map(|parsed| parsed.marker_line)
            .unwrap_or_else(|| attention.body_markdown.clone());
        let (summary, reason) = crate::deferred_scope::summary_and_reason(&marker_line);
        let summary_text = summary.unwrap_or_else(|| "(summary not parseable — see marker below)".to_owned());
        let reason_text = reason.unwrap_or_else(|| "(reason not parseable — see marker below)".to_owned());

        let name = format!("Deferred: {}", truncate_chars(&summary_text, 100));
        let pr_number = source_task
            .pr_url
            .as_deref()
            .and_then(boss_github::pr_url::pr_number_from_url)
            .map(|n| n as i64);
        let pr_suffix = source_task
            .pr_url
            .as_deref()
            .map(|url| format!(", PR {url}"))
            .unwrap_or_default();
        let description = format!(
            "Deferred scope from {source_id} (\"{source_name}\").\n\n\
             **Deferred:** {summary_text}\n\n\
             **Reason:** {reason_text}\n\n\
             ---\n\
             Filed from attention item `{attention_id}` via \"Create task\" on the deferred-scope \
             marker recorded by execution `{execution_id}`{pr_suffix}.\n\n\
             Marker (verbatim):\n\n```\n{marker_line}\n```",
            source_id = source_task.id,
            source_name = source_task.name,
        );

        let new_task = insert_chore_in_tx(
            &tx,
            CreateChoreInput::builder()
                .product_id(source_task.product_id.clone())
                .name(name)
                .maybe_description(Some(description))
                .created_via(CREATED_VIA_ATTENTION)
                .force_duplicate(true)
                .maybe_priority(Some(source_task.priority.clone()))
                .maybe_repo_remote_url(source_task.repo_remote_url.clone())
                .maybe_kind_override(Some(TaskKind::Followup))
                .maybe_origin_task_short_id(source_task.short_id)
                .maybe_origin_pr_number(pr_number)
                .build(),
        )?;

        let now = now_string();
        tx.execute(
            "UPDATE work_attention_items
             SET status = 'converted', resolved_at = ?2, converted_task_id = ?3
             WHERE id = ?1",
            params![attention_id, now, new_task.id],
        )?;
        let updated = query_attention_item(&tx, attention_id)?
            .with_context(|| format!("missing attention item after update: {attention_id}"))?;
        tx.commit()?;
        Ok((updated, new_task))
    }

    /// Every open `deferred_scope` attention item across `product_id`,
    /// paired with the id of the work item whose execution recorded it.
    /// Deferred-scope items carry only `execution_id` (never
    /// `work_item_id` — see [`WorkAttentionItem::work_item_id`]), so this
    /// crosses the execution→work-item join
    /// [`Self::list_attention_items_for_work_item`] doesn't need. Backs
    /// the kanban review-lane card affordance (badge + popup) and the
    /// first-class deferred-scope presentation.
    pub fn list_open_deferred_scope_attentions_for_product(
        &self,
        product_id: &str,
    ) -> Result<Vec<DeferredScopeAttention>> {
        let conn = self.connect()?;
        let mut stmt = conn.prepare(
            "SELECT ai.id, ai.execution_id, ai.work_item_id, ai.kind, ai.status, ai.title, ai.body_markdown,
                    ai.created_at, ai.resolved_at, ai.converted_task_id, we.work_item_id
             FROM work_attention_items ai
             JOIN work_executions we ON we.id = ai.execution_id
             JOIN tasks t ON t.id = we.work_item_id
             WHERE t.product_id = ?1
               AND t.deleted_at IS NULL
               AND ai.kind = ?2
               AND ai.status = 'open'
             ORDER BY ai.created_at ASC, ai.id ASC",
        )?;
        let rows = stmt.query_map(
            params![product_id, crate::deferred_scope::DEFERRED_SCOPE_ATTENTION_KIND],
            |row| {
                Ok(DeferredScopeAttention {
                    item: map_attention_item(row)?,
                    source_work_item_id: row.get(10)?,
                })
            },
        )?;
        collect_rows(rows)
    }

    pub fn update_work_item(&self, id: &str, patch: WorkItemPatch) -> Result<WorkItem> {
        self.update_work_item_as_actor(id, patch, "human")
    }

    /// Like `update_work_item` but stamps `last_status_actor` with `actor`
    /// when the status actually changes. Engine-internal writers use direct
    /// SQL with `last_status_actor = 'engine'`; this path is for peer RPCs
    /// where the caller tier has already been resolved to `"human"` or
    /// `"boss"`.
    pub fn update_work_item_as_actor(&self, id: &str, patch: WorkItemPatch, actor: &str) -> Result<WorkItem> {
        match classify_id(id)? {
            ItemKind::Product => self.update_product(id, patch),
            ItemKind::Project => self.update_project(id, patch, actor),
            ItemKind::Task => self.update_task(id, patch, actor),
        }
    }

    /// Soft-delete a task/chore (and cascade to its revision chain).
    /// Returns every id this call tombstoned — `id` itself followed by
    /// any cascade-deleted revision ids — so a caller that needs to
    /// tear down live workers bound to the deleted rows (a revision can
    /// have its own execution, independent of the parent's) knows the
    /// full set to check, not just the top-level id.
    pub fn delete_work_item(&self, id: &str) -> Result<Vec<String>> {
        self.delete_work_item_as_actor(id, LAST_STATUS_ACTOR_HUMAN)
    }

    /// Like [`Self::delete_work_item`] but attributes the soft-delete to
    /// `actor`. When that actor is Boothby the tombstone is captured as a
    /// `boothby_actions` row (pre/post image of `deleted_at`) inside the
    /// same transaction, so closing a stale task is undoable.
    ///
    /// Only the parent's tombstone is audited, not the cascade-deleted
    /// revisions: [`Self::restore_work_item`] restores that whole cascade
    /// from the parent's `deleted_at` timestamp, so the parent's action
    /// row is already sufficient to undo the entire operation. Emitting an
    /// action per revision would imply each is separately undoable, which
    /// is not how restore works.
    pub fn delete_work_item_as_actor(&self, id: &str, actor: &str) -> Result<Vec<String>> {
        match classify_id(id)? {
            ItemKind::Task => {
                let mut conn = self.connect()?;
                let tx = conn.transaction()?;
                let now = now_string();
                // Pre-image, before the tombstone lands. Only read when the
                // actor is Boothby — every other caller pays nothing.
                let before = if boothby::is_boothby_actor(actor) {
                    query_task(&tx, id)?
                } else {
                    None
                };
                let rows = tx.execute(
                    "UPDATE tasks SET deleted_at = ?2, updated_at = ?2
                     WHERE id = ?1 AND deleted_at IS NULL",
                    params![id, now],
                )?;
                if rows == 0 {
                    bail!("unknown task: {id}");
                }
                // Cascade soft-delete to every revision in the chain
                // (BFS over parent_task_id links). A live revision is
                // meaningless once its parent is gone — it can only ever
                // amend the parent's PR, which no longer exists — and
                // leaves board noise / dispatch hazards.
                // Use the same `now` timestamp so restore can identify
                // which revisions were cascade-deleted alongside this parent.
                let revision_ids = collect_chain_revision_ids(&tx, id)?;
                for rev_id in &revision_ids {
                    tx.execute(
                        "UPDATE tasks SET deleted_at = ?2, updated_at = ?2
                         WHERE id = ?1 AND deleted_at IS NULL",
                        params![rev_id, now],
                    )?;
                }
                // Q10 (deleted prereq): drop every dependency edge that
                // names this task as either endpoint. A row with a
                // tombstoned prerequisite is the worst of both worlds —
                // dependents stuck on a row that is no longer a thing.
                tx.execute(
                    "DELETE FROM work_item_dependencies
                     WHERE dependent_id = ?1 OR prerequisite_id = ?1",
                    params![id],
                )?;
                if let Some(before) = before {
                    let after = query_task(&tx, id).require("task", id)?;
                    boothby::capture_task_update(&tx, self, actor, &before, &after, &now)?;
                }
                tx.commit()?;
                let mut tombstoned_ids = vec![id.to_owned()];
                tombstoned_ids.extend(revision_ids);
                Ok(tombstoned_ids)
            }
            ItemKind::Product => bail!("product deletion is not supported; archive it instead"),
            ItemKind::Project => bail!("project deletion is not supported; archive it instead"),
        }
    }

    /// Inverse of [`Self::delete_work_item`]: clear the `deleted_at`
    /// tombstone on a soft-deleted task so it becomes visible again.
    /// Accepts a canonical `task_…` id or a friendly short id (`T43`);
    /// the friendly resolution deliberately includes soft-deleted rows
    /// so a tombstoned task is still findable. Idempotent — restoring a
    /// row that is already live succeeds as a no-op. Returns the now-live
    /// work item.
    ///
    /// Cascade-restore: child revisions whose `deleted_at` matches the
    /// parent's tombstone timestamp were cascade-deleted by
    /// [`Self::delete_work_item`] and are restored together with the
    /// parent in the same transaction. Revisions that were independently
    /// deleted (different timestamp) are left tombstoned.
    ///
    /// Note: the dependency edges that `delete_work_item` dropped are
    /// NOT recreated — they were deleted outright, not tombstoned, so a
    /// restored task comes back with no dependency edges. The operator
    /// must re-add any that still matter.
    pub fn restore_work_item(&self, id: &str) -> Result<WorkItem> {
        self.restore_work_item_as_actor(id, LAST_STATUS_ACTOR_HUMAN)
    }

    /// Like [`Self::restore_work_item`] but attributes the restore to
    /// `actor`, auditing it as a `boothby_actions` row when that actor is
    /// Boothby. See [`Self::delete_work_item_as_actor`] for why only the
    /// parent — not each cascade-restored revision — is audited.
    pub fn restore_work_item_as_actor(&self, id: &str, actor: &str) -> Result<WorkItem> {
        let mut conn = self.connect()?;
        let canonical = resolve_friendly_work_item_id_inner(&conn, id, true)?.unwrap_or_else(|| id.to_owned());
        match classify_id(&canonical)? {
            ItemKind::Task => {
                // The row must exist (live or tombstoned). A WHERE that
                // matched only tombstoned rows would make an idempotent
                // re-restore indistinguishable from an unknown id, so we
                // check existence separately before the conditional
                // UPDATE.
                let exists = conn
                    .query_row("SELECT 1 FROM tasks WHERE id = ?1", params![canonical], |_| Ok(()))
                    .optional()?
                    .is_some();
                if !exists {
                    bail!("unknown task: {canonical}");
                }
                // Capture the parent's current deleted_at before restoring.
                // Revisions with the same timestamp were cascade-deleted by
                // delete_work_item and should be restored alongside the parent.
                let parent_deleted_at: Option<String> = conn
                    .query_row(
                        "SELECT deleted_at FROM tasks WHERE id = ?1",
                        params![canonical],
                        |row| row.get(0),
                    )
                    .optional()?
                    .flatten();
                let now = now_string();
                {
                    let tx = conn.transaction()?;
                    // Pre-image, while the tombstone is still on the row.
                    // Only read for Boothby; every other caller pays nothing.
                    let before = if boothby::is_boothby_actor(actor) {
                        query_task(&tx, &canonical)?
                    } else {
                        None
                    };
                    tx.execute(
                        "UPDATE tasks SET deleted_at = NULL, updated_at = ?2
                         WHERE id = ?1 AND deleted_at IS NOT NULL",
                        params![canonical, now],
                    )?;
                    // BFS to restore all cascade-deleted revisions that share
                    // the parent's tombstone timestamp. Revisions deleted
                    // independently (different deleted_at) are left tombstoned.
                    if let Some(ref deleted_at) = parent_deleted_at {
                        let mut frontier = vec![canonical.clone()];
                        for _ in 0..64 {
                            if frontier.is_empty() {
                                break;
                            }
                            let mut next = Vec::new();
                            for ancestor_id in &frontier {
                                let children: Vec<String> = tx
                                    .prepare_cached(
                                        "SELECT id FROM tasks
                                         WHERE parent_task_id = ?1
                                           AND kind = 'revision'
                                           AND deleted_at = ?2",
                                    )?
                                    .query_map(params![ancestor_id, deleted_at], |row| row.get(0))?
                                    .filter_map(|r| r.ok())
                                    .collect();
                                for child_id in children {
                                    tx.execute(
                                        "UPDATE tasks SET deleted_at = NULL, updated_at = ?2
                                         WHERE id = ?1",
                                        params![child_id, now],
                                    )?;
                                    next.push(child_id);
                                }
                            }
                            frontier = next;
                        }
                    }
                    if let Some(before) = before {
                        let after = query_task(&tx, &canonical).require("task", &canonical)?;
                        boothby::capture_task_update(&tx, self, actor, &before, &after, &now)?;
                    }
                    tx.commit()?;
                }
                query_task(&conn, &canonical)?
                    .map(task_to_item)
                    .with_context(|| format!("unknown task: {canonical}"))
            }
            ItemKind::Product => {
                bail!("products are archived, not soft-deleted; nothing to restore")
            }
            ItemKind::Project => {
                bail!("projects are archived, not soft-deleted; nothing to restore")
            }
        }
    }

    pub fn get_work_tree(&self, product_id: &str) -> Result<WorkTree> {
        // Uninstrumented path (tests, single-item callers): run the same
        // body against a disabled trace that records and emits nothing.
        let mut trace = PopulationTrace::disabled();
        self.get_work_tree_instrumented(product_id, &mut trace)
    }

    /// Body of [`get_work_tree`] with per-segment wall-clock instrumentation
    /// threaded through `trace`. The production `handle_get_work_tree` path
    /// passes an enabled trace (see [`crate::population_timing`]); every
    /// other caller goes through the wrapper above with a disabled trace, so
    /// the timing is genuinely free off the RPC path.
    pub fn get_work_tree_instrumented(&self, product_id: &str, trace: &mut PopulationTrace) -> Result<WorkTree> {
        let conn = self.connect()?;

        let t = Instant::now();
        let product = query_product(&conn, product_id).require("product", product_id)?;
        trace.record_query(segment::DB_PRODUCT, elapsed_ms(t), 1);

        let t = Instant::now();
        let projects = {
            let mut stmt = conn.prepare(
                "SELECT id, product_id, name, slug, description, goal, status, priority, created_at, updated_at, last_status_actor,
                        design_doc_repo_remote_url, design_doc_branch, design_doc_path, short_id
                 FROM projects
                 WHERE product_id = ?1
                 ORDER BY created_at ASC, name COLLATE NOCASE ASC",
            )?;
            let rows = stmt.query_map([product_id], map_project)?;
            collect_rows(rows)?
        };
        trace.record_query(segment::DB_PROJECTS, elapsed_ms(t), projects.len());

        let t = Instant::now();
        let tasks = {
            // `kind IN ('project_task', 'design')` — the design task
            // auto-created at project birth lives in the same lane as
            // every other project task. Sorting on `ordinal` ASC puts
            // the design task (ordinal = 0) at the head of the
            // project's task chain, which matches the kanban
            // expectation that design lands first.
            let mut stmt = conn.prepare(
                "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver, external_ref_kind, external_ref_canonical_id, external_ref_raw, external_ref_synced_at, external_ref_unbound_at, parent_task_id, source_automation_id, origin_task_short_id, origin_pr_number, completed_at, dispatch_failed_reason, dispatch_failed_error, dispatch_failed_at, blocked_detail
                 FROM tasks
                 WHERE product_id = ?1 AND kind IN ('project_task', 'design', 'investigation', 'revision', 'design_postmortem') AND deleted_at IS NULL AND status != 'archived'
                 ORDER BY COALESCE(ordinal, 0) ASC, created_at ASC",
            )?;
            let rows = stmt.query_map([product_id], map_task_with_external_ref_parent_source_and_provenance)?;
            collect_rows(rows)?
        };
        trace.record_query(segment::DB_TASKS, elapsed_ms(t), tasks.len());

        let t = Instant::now();
        let mut chores = {
            // `status != 'archived'` keeps archived leaf items off the
            // kanban board (same treatment as archived projects), while
            // leaving them queryable/listable via `boss task|chore list
            // --include-archived` (they are NOT tombstoned, unlike delete).
            let mut stmt = conn.prepare(
                "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver, external_ref_kind, external_ref_canonical_id, external_ref_raw, external_ref_synced_at, external_ref_unbound_at, parent_task_id, source_automation_id, origin_task_short_id, origin_pr_number, completed_at, dispatch_failed_reason, dispatch_failed_error, dispatch_failed_at, blocked_detail
                 FROM tasks
                 WHERE product_id = ?1 AND kind IN ('chore', 'followup') AND deleted_at IS NULL AND status != 'archived'
                 ORDER BY created_at ASC",
            )?;
            let rows = stmt.query_map([product_id], map_task_with_external_ref_parent_source_and_provenance)?;
            collect_rows(rows)?
        };
        trace.record_query(segment::DB_CHORES, elapsed_ms(t), chores.len());

        // Carry the total item count on every aggregate segment so cost
        // correlates with cardinality (parity with the app-side `items`).
        trace.set_items(tasks.len() + chores.len());

        // Primary N+1: one runtime lookup per task and chore, each running
        // 1-3 point queries. `runtime_queries` is the aggregate statement
        // count, which makes the per-row fan-out visible in the log.
        let t = Instant::now();
        let (task_runtimes, runtime_queries) = collect_task_runtimes(&conn, &tasks, &chores)?;
        trace.record_nplus1(
            segment::DB_TASK_RUNTIMES,
            elapsed_ms(t),
            tasks.len() + chores.len(),
            runtime_queries,
        );

        let t = Instant::now();
        let dependencies = collect_product_dependencies(&conn, product_id)?;
        trace.record_query(segment::DB_DEPENDENCIES, elapsed_ms(t), dependencies.len());

        // Compute revision projections (revision_seq, revision_parent_pr_url)
        // for every `kind = 'revision'` task. These are derived fields —
        // not stored columns — so they are calculated fresh here.
        let t = Instant::now();
        let mut tasks = attach_revision_projections(tasks, &chores);
        // Compute has_in_progress_revision for every chain-root task that
        // has at least one todo/active descendant revision.
        attach_in_progress_revision_flag(&mut tasks, &mut chores);
        trace.record_plain(segment::ASSEMBLE, elapsed_ms(t));

        // Compute ai_reviewing for tasks held in Doing while a pr_review
        // execution is in flight. Surfaces the "Reviewing (AI)" badge on
        // the kanban card. Errors are non-fatal — log and continue with
        // the field defaulting to false. Single batched `IN (...)` query.
        let t = Instant::now();
        if let Err(err) = attach_ai_reviewing_flag(&conn, &mut tasks, &mut chores) {
            tracing::warn!(?err, "get_work_tree: failed to attach ai_reviewing flag; ignoring");
        }
        trace.record_plain(segment::DB_AI_REVIEWING, elapsed_ms(t));

        // Resolve the per-task doc-link state for project-less docs-backed
        // items (investigations / project-less designs) so their card renders
        // the Review-lane doc-link icon — parity with design cards, whose
        // state is resolved from the parent project's `design_doc_*` columns.
        // Pass `|_| None` for the workspace lookup: cube is not consulted in
        // get_work_tree, and the app prefers the GitHub raw-content URL for
        // in-review docs on the PR head branch anyway. Errors per task are
        // non-fatal — log and leave the field None (affordance hidden).
        //
        // Secondary, gated N+1: only the docs-backed subset enters
        // `resolve_task_doc_pointer` (2-3 queries each). `resolved` is the
        // number of items that did, i.e. the rows this loop touched;
        // `doc_pointer_queries` is the aggregate statement count across all
        // of them, exposing the per-row fan-out the same way
        // `db.task_runtimes` does.
        let t = Instant::now();
        let mut resolved = 0usize;
        let mut doc_pointer_queries = 0u64;
        for task in &mut tasks {
            if !crate::design_detector::task_uses_per_task_doc(&task.kind, task.project_id.is_none()) {
                continue;
            }
            resolved += 1;
            match resolve_task_doc_pointer(&conn, &task.id, |_| None, &mut doc_pointer_queries) {
                Ok(state) => task.doc_link_state = state,
                Err(err) => tracing::warn!(
                    task_id = %task.id,
                    ?err,
                    "get_work_tree: failed to resolve task doc-link state; leaving affordance hidden"
                ),
            }
        }
        trace.record_nplus1(segment::DB_DOC_POINTERS, elapsed_ms(t), resolved, doc_pointer_queries);

        Ok(WorkTree {
            product,
            projects,
            tasks,
            chores,
            task_runtimes,
            dependencies,
        })
    }

    pub fn reorder_project_tasks(&self, project_id: &str, task_ids: &[String]) -> Result<()> {
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        ensure_project_exists(&tx, project_id)?;

        let mut existing = {
            let mut stmt = tx.prepare(
                "SELECT id
                 FROM tasks
                 WHERE project_id = ?1 AND kind = 'project_task' AND deleted_at IS NULL
                 ORDER BY COALESCE(ordinal, 0) ASC, created_at ASC",
            )?;
            let rows = stmt.query_map([project_id], |row| row.get::<_, String>(0))?;
            collect_rows(rows)?
        };
        let mut requested = task_ids.to_vec();
        existing.sort();
        requested.sort();
        if existing != requested {
            bail!("reorder request must include the full active task set for the project");
        }

        for (index, task_id) in task_ids.iter().enumerate() {
            tx.execute(
                "UPDATE tasks SET ordinal = ?2, updated_at = ?3 WHERE id = ?1",
                params![task_id, (index as i64) + 1, now_string()],
            )?;
        }

        tx.commit()?;
        Ok(())
    }

    pub fn get_work_item(&self, id: &str) -> Result<WorkItem> {
        let conn = self.connect()?;
        match classify_id(id)? {
            ItemKind::Product => query_product(&conn, id)?
                .map(WorkItem::Product)
                .with_context(|| format!("unknown product: {id}")),
            ItemKind::Project => query_project(&conn, id)?
                .map(WorkItem::Project)
                .with_context(|| format!("unknown project: {id}")),
            ItemKind::Task => query_task(&conn, id)?
                .filter(|task| task.deleted_at.is_none())
                .map(task_to_item)
                .with_context(|| format!("unknown task: {id}")),
        }
    }

    /// Whether the row backing `id` is genuinely gone — either no such
    /// row was ever inserted, or (for a task/chore) its `deleted_at`
    /// tombstone is set by [`Self::delete_work_item`]'s soft-delete.
    /// Products and projects can't be deleted (`delete_work_item`
    /// rejects both), so this is always `Ok(false)` for them.
    ///
    /// [`get_work_item`] collapses "row never existed" and "DB query
    /// failed" into the same generic `unknown …` error, which is fine
    /// for most callers but not for a reconciler that must reap on
    /// "confirmed gone" while staying conservative on "DB hiccuped".
    /// The terminal-work sweep calls this after a `get_work_item`
    /// failure to tell the two cases apart: `Ok(true)` means the
    /// binding is a genuine orphan (the row was deleted out from under
    /// a live execution); `Ok(false)` or `Err` means treat the failure
    /// the old conservative way and retry next pass.
    pub fn work_item_row_missing(&self, id: &str) -> Result<bool> {
        let conn = self.connect()?;
        match classify_id(id)? {
            ItemKind::Task => Ok(match query_task(&conn, id)? {
                None => true,
                Some(task) => task.deleted_at.is_some(),
            }),
            ItemKind::Product | ItemKind::Project => Ok(false),
        }
    }

    /// Look up a work item by canonical id or short-form (`T42`,
    /// `t42`). Returns `Ok(None)` when no item matches, `Ok(Some(…))`
    /// on success. Canonical ids are passed straight to
    /// [`get_work_item`]; short-form ids are first resolved via
    /// [`resolve_friendly_work_item_id`] and then fetched by canonical
    /// id. Unlike `get_work_item`, this never calls `classify_id`, so
    /// it accepts both forms without the caller choosing.
    pub fn get_work_item_resolving_short_id(&self, id: &str) -> Result<Option<WorkItem>> {
        let canonical = {
            let conn = self.connect()?;
            resolve_friendly_work_item_id(&conn, id)?.unwrap_or_else(|| id.to_owned())
        };
        match classify_id(&canonical) {
            Ok(_) => match self.get_work_item(&canonical) {
                Ok(item) => Ok(Some(item)),
                Err(_) => Ok(None),
            },
            Err(_) => Ok(None),
        }
    }

    /// Single-item version of the per-task runtime data carried in
    /// `WorkTree::task_runtimes`. Backs the `GetTaskRuntime` RPC that
    /// `boss chore show` / `boss task show` use to surface the active
    /// execution + run on the rendered work item. The lookup never
    /// fails on missing executions: an untouched work item simply
    /// returns a `TaskRuntime` with every `Option` field set to
    /// `None`. Friendly ids (`T42`, `boss/42`) are resolved to primary
    /// ids before the query runs, matching `get_work_item`'s contract.
    pub fn get_task_runtime(&self, work_item_id: &str) -> Result<TaskRuntime> {
        let conn = self.connect()?;
        let resolved = resolve_friendly_work_item_id(&conn, work_item_id)?.unwrap_or_else(|| work_item_id.to_owned());
        // Single-item lookup; the per-item subquery tally is only meaningful
        // for the `get_work_tree` N+1, so discard it here.
        let mut queries = 0u64;
        query_task_runtime(&conn, &resolved, &mut queries)
    }

    /// Look up a work item by its per-product short_id. Searches both
    /// the `tasks` table (returning `Task` or `Chore`) and the
    /// `projects` table, returning the first match. Returns `None` if
    /// no row with `(product_id, short_id)` exists.
    ///
    /// The per-product sequence is shared across tasks and projects
    /// (design Q1), so each short_id belongs to at most one row across
    /// both tables for a given product.
    pub fn get_work_item_by_short_id(&self, product_id: &str, short_id: i64) -> Result<Option<WorkItem>> {
        let conn = self.connect()?;
        if let Some(task) = conn
            .query_row(
                "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver, parent_task_id, origin_task_short_id, origin_pr_number, completed_at, archived_reason, dispatch_failed_reason, dispatch_failed_error, dispatch_failed_at, blocked_detail
                 FROM tasks
                 WHERE product_id = ?1 AND short_id = ?2 AND deleted_at IS NULL",
                params![product_id, short_id],
                map_task_with_parent_provenance_and_archived_reason,
            )
            .optional()?
        {
            return Ok(Some(task_to_item(task)));
        }
        if let Some(project) = conn
            .query_row(
                "SELECT id, product_id, name, slug, description, goal, status, priority, created_at, updated_at, last_status_actor,
                        design_doc_repo_remote_url, design_doc_branch, design_doc_path, short_id
                 FROM projects
                 WHERE product_id = ?1 AND short_id = ?2",
                params![product_id, short_id],
                map_project,
            )
            .optional()?
        {
            return Ok(Some(WorkItem::Project(project)));
        }
        Ok(None)
    }

    /// Find every work item bound to GitHub PR number `pr_number`,
    /// together with the revisions in each match's chain.
    ///
    /// Unlike [`Self::list_tasks`] / [`Self::list_chores`] this scans
    /// the entire `tasks` table — all kinds (`project_task`, `chore`,
    /// `design`, `investigation`, `revision`) across every product — so
    /// a chore- or revision-backed PR is just as findable as a project
    /// task. The PR number is parsed from each row's stored `pr_url`
    /// using the same parser the merge poller uses, so query strings and
    /// fragments are tolerated. Revision tasks normally carry no
    /// `pr_url` (they surface inside a matched owner's `revisions`
    /// list), but may have one in exceptional engine recovery paths
    /// (e.g. the double-spawn race recovery), in which case they appear
    /// as owners too.
    ///
    /// Soft-deleted rows are excluded from both owners and revisions.
    /// Returns an empty vec when no row is bound to the PR number. More
    /// than one element may mean the same PR number exists in multiple
    /// repos, or that same-repo same-PR multiplicity occurred (e.g. a
    /// chore owner and a revision that each carry the URL). The caller
    /// must display all matches; `--repo` is an optional filter, not a
    /// required disambiguator.
    pub fn find_work_items_by_pr(&self, pr_number: i64) -> Result<Vec<PrWorkItemMatch>> {
        let conn = self.connect()?;
        // Owners: any live row carrying a pr_url. We parse the number in
        // Rust (rather than a SQL LIKE) so the match is identical to the
        // merge poller's and robust to `?`/`#` suffixes.
        let owners: Vec<Task> = {
            let mut stmt = conn.prepare(
                "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver, parent_task_id
                 FROM tasks
                 WHERE pr_url IS NOT NULL AND pr_url != '' AND deleted_at IS NULL
                 ORDER BY created_at ASC",
            )?;
            let rows = stmt.query_map([], map_task_with_parent)?;
            collect_rows(rows)?
                .into_iter()
                .filter(|task| task.pr_url.as_deref().and_then(crate::merge_poller::parse_pr_number) == Some(pr_number))
                .collect()
        };

        let mut matches = Vec::with_capacity(owners.len());
        for owner in owners {
            // Gather every revision in this owner's chain (BFS over
            // parent_task_id) and annotate them with revision_seq /
            // revision_parent_pr_url so the caller can render R1, R2, ….
            let revision_ids = collect_chain_revision_ids(&conn, &owner.id)?;
            let mut revisions = Vec::with_capacity(revision_ids.len());
            for rev_id in &revision_ids {
                if let Some(task) = query_task(&conn, rev_id)?
                    && task.deleted_at.is_none()
                {
                    revisions.push(task);
                }
            }
            let mut revisions = attach_revision_projections(revisions, std::slice::from_ref(&owner));
            revisions.sort_by_key(|rev| rev.revision_seq.unwrap_or(i64::MAX));
            matches.push(PrWorkItemMatch { owner, revisions });
        }
        Ok(matches)
    }

    pub fn list_tasks(
        &self,
        product_id: &str,
        project_id: Option<&str>,
        dep_filter: Option<&DependencyFilter>,
        include_deleted: bool,
    ) -> Result<Vec<Task>> {
        let conn = self.connect()?;
        ensure_product_exists(&conn, product_id)?;

        // The soft-delete predicate is dropped entirely (rather than
        // negated) when the caller asks to include deleted rows, so the
        // default `--deleted` view shows live and tombstoned tasks
        // together. Restore acts on the tombstoned ones.
        let deleted_clause = if include_deleted { "" } else { " AND deleted_at IS NULL" };
        let kind_clause = list_tasks_kind_filter_sql();

        let mut tasks = if let Some(project_id) = project_id {
            ensure_project_belongs_to_product(&conn, project_id, product_id)?;
            let mut stmt = conn.prepare(&format!(
                "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver
                 FROM tasks
                 WHERE product_id = ?1 AND project_id = ?2 AND kind IN ({kind_clause}){deleted_clause}
                 ORDER BY COALESCE(ordinal, 0) ASC, created_at ASC",
            ))?;
            let rows = stmt.query_map(params![product_id, project_id], map_task)?;
            collect_rows(rows)?
        } else {
            let mut stmt = conn.prepare(&format!(
                "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver
                 FROM tasks
                 WHERE product_id = ?1 AND kind IN ({kind_clause}){deleted_clause}
                 ORDER BY COALESCE(ordinal, 0) ASC, created_at ASC",
            ))?;
            let rows = stmt.query_map([product_id], map_task)?;
            collect_rows(rows)?
        };

        if let Some(filter) = dep_filter {
            apply_dep_filter(
                &conn,
                filter,
                |task: &Task| task.id.as_str(),
                |task: &Task| task.status.as_str(),
                &mut tasks,
            )?;
        }
        Ok(tasks)
    }

    /// Look up a cached pane-titlebar summary for a work item.
    /// Returns `(summary, basis_hash)` so callers can compare the
    /// stored basis against a freshly computed one to decide whether
    /// the cache is still valid.
    /// Read a value from the engine's metadata KV. Returns `None` if
    /// the key has never been written. Used by the engine for small
    /// persisted settings (live-status disabled slot list, schema
    /// version, etc.) that don't deserve their own table.
    pub fn get_metadata(&self, key: &str) -> Result<Option<String>> {
        let conn = self.connect()?;
        let row = conn
            .query_row("SELECT value FROM metadata WHERE key = ?1", params![key], |row| {
                row.get::<_, String>(0)
            })
            .optional()?;
        Ok(row)
    }

    /// Insert-or-replace a metadata value. The metadata table is the
    /// engine-side KV store — schema version, persisted live-status
    /// disabled slots, anything that needs to outlive the process
    /// without justifying a dedicated table.
    pub fn set_metadata(&self, key: &str, value: &str) -> Result<()> {
        let conn = self.connect()?;
        conn.execute(
            "INSERT INTO metadata (key, value) VALUES (?1, ?2)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            params![key, value],
        )?;
        Ok(())
    }

    pub fn get_pane_summary(&self, work_item_id: &str) -> Result<Option<(String, String)>> {
        let conn = self.connect()?;
        let row = conn
            .query_row(
                "SELECT summary, basis_hash FROM pane_summaries WHERE work_item_id = ?1",
                params![work_item_id],
                |row| Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?)),
            )
            .optional()?;
        Ok(row)
    }

    /// Insert or replace the cached pane summary for a work item.
    /// `basis_hash` should be derived from the inputs that, if
    /// changed, invalidate the cached summary (typically a hash of
    /// name + description).
    pub fn set_pane_summary(&self, work_item_id: &str, summary: &str, basis_hash: &str) -> Result<()> {
        let conn = self.connect()?;
        conn.execute(
            "INSERT INTO pane_summaries (work_item_id, summary, basis_hash, created_at)
             VALUES (?1, ?2, ?3, ?4)
             ON CONFLICT(work_item_id) DO UPDATE SET
                 summary = excluded.summary,
                 basis_hash = excluded.basis_hash,
                 created_at = excluded.created_at",
            params![work_item_id, summary, basis_hash, now_string()],
        )?;
        Ok(())
    }

    /// List `kind = 'revision'` rows for a product. Revisions are excluded
    /// from `list_tasks` and `list_chores` by design; this is the only bulk
    /// enumeration path. Optionally restrict to a single parent via
    /// `parent_id`.
    pub fn list_revisions(
        &self,
        product_id: &str,
        dep_filter: Option<&DependencyFilter>,
        include_deleted: bool,
        parent_id: Option<&str>,
    ) -> Result<Vec<Task>> {
        let conn = self.connect()?;
        ensure_product_exists(&conn, product_id)?;

        let deleted_clause = if include_deleted { "" } else { " AND deleted_at IS NULL" };
        let parent_clause = if parent_id.is_some() {
            " AND parent_task_id = ?2"
        } else {
            ""
        };
        let mut stmt = conn.prepare(&format!(
            "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver, parent_task_id, origin_task_short_id, origin_pr_number, completed_at
             FROM tasks
             WHERE product_id = ?1 AND kind = 'revision'{deleted_clause}{parent_clause}
             ORDER BY created_at ASC",
        ))?;
        let mut revisions: Vec<Task> = if let Some(parent_id) = parent_id {
            let rows = stmt.query_map(params![product_id, parent_id], map_task_with_parent_and_provenance)?;
            collect_rows(rows)?
        } else {
            let rows = stmt.query_map([product_id], map_task_with_parent_and_provenance)?;
            collect_rows(rows)?
        };
        if let Some(filter) = dep_filter {
            apply_dep_filter(
                &conn,
                filter,
                |revision: &Task| revision.id.as_str(),
                |revision: &Task| revision.status.as_str(),
                &mut revisions,
            )?;
        }
        Ok(revisions)
    }

    pub fn list_chores(
        &self,
        product_id: &str,
        dep_filter: Option<&DependencyFilter>,
        include_deleted: bool,
    ) -> Result<Vec<Task>> {
        let conn = self.connect()?;
        ensure_product_exists(&conn, product_id)?;

        // See `list_tasks` for the include-deleted contract.
        let deleted_clause = if include_deleted { "" } else { " AND deleted_at IS NULL" };
        let mut stmt = conn.prepare(&format!(
            "SELECT id, product_id, project_id, kind, name, description, status, ordinal, pr_url, deleted_at, created_at, updated_at, autostart, last_status_actor, priority, created_via, blocked_reason, blocked_attempt_id, repo_remote_url, effort_level, model_override, ci_attempt_budget, ci_attempts_used, short_id, ci_required_state, review_required_state, ci_required_detail, review_required_detail, pr_state_polled_at, merge_queue_state, merge_queue_detail, driver, parent_task_id, origin_task_short_id, origin_pr_number, completed_at
             FROM tasks
             WHERE product_id = ?1 AND kind IN ('chore', 'followup'){deleted_clause}
             ORDER BY created_at ASC",
        ))?;
        let rows = stmt.query_map([product_id], map_task_with_parent_and_provenance)?;
        let mut chores: Vec<Task> = collect_rows(rows)?;
        if let Some(filter) = dep_filter {
            apply_dep_filter(
                &conn,
                filter,
                |chore: &Task| chore.id.as_str(),
                |chore: &Task| chore.status.as_str(),
                &mut chores,
            )?;
        }
        Ok(chores)
    }

    /// Read the unsatisfied prerequisites of `work_item_id` outside
    /// of any in-flight transaction. Used by the engine app to refuse
    /// `RequestExecution` against a gated work item (see
    /// `boss::engine::app`).
    pub fn gating_prereqs_for(&self, work_item_id: &str) -> Result<Vec<String>> {
        let conn = self.connect()?;
        deps::gating_prereqs_for(&conn, work_item_id)
    }

    /// The `merge_order` siblings of `work_item_id` that have already merged
    /// (`status = 'done'`), each with its PR url. Non-blocking: reads the
    /// soft `merge_order` pairing graph, never the `blocks` gating graph.
    ///
    /// Used by the forward-port brief composer to stamp a sibling-specific
    /// preservation clause: because the named siblings landed *first* and
    /// overlap this item's files, their surfaces must be preserved by this
    /// item's forward-port (the both-parents deletion tripwire then verifies
    /// it). Returns an empty vec when the item has no merged overlap partner.
    pub fn merge_order_merged_siblings(&self, work_item_id: &str) -> Result<Vec<deps::MergeOrderMergedSibling>> {
        let conn = self.connect()?;
        let mut out = Vec::new();
        for sib in deps::merge_order_siblings(&conn, work_item_id)? {
            // Only task rows can carry a merged PR.
            if !sib.sibling_id.starts_with("task_") {
                continue;
            }
            if let Some(task) = query_task(&conn, &sib.sibling_id)?
                && task.status == TaskStatus::Done
            {
                out.push(deps::MergeOrderMergedSibling {
                    task_id: task.id,
                    pr_url: task.pr_url,
                });
            }
        }
        Ok(out)
    }

    /// Declare a `relation` edge from `dependent` to `prerequisite`.
    /// Validates both endpoints resolve to live work items in the
    /// same product, refuses self-edges and cycles, and is
    /// idempotent on a re-add of an existing edge.
    ///
    /// v1 ships only `relation = 'blocks'`. The CLI accepts an
    /// explicit `--relation` flag but rejects anything else; the
    /// column accepts any TEXT value at the schema level so future
    /// relation types can ship without a re-migration.
    pub fn add_dependency(&self, input: AddDependencyInput) -> Result<WorkItemDependency> {
        self.add_dependency_with_worker_reconcile(input).map(|(edge, _)| edge)
    }

    /// Like [`Self::add_dependency`], but also returns the live
    /// execution (if any) that was cancelled because the new edge
    /// pushed an actively-running dependent into `blocked`.
    ///
    /// The DB transition is atomic: when this returns `Some(execution)`,
    /// the dependent is already `blocked` and the execution is already
    /// `cancelled` in the database. The caller (engine app handler)
    /// MUST still release the worker's pane and cube workspace lease via
    /// `CompletionHandler::force_release` — those are async side effects
    /// that cannot live inside the DB transaction. The plain
    /// `add_dependency` wrapper discards this and is only safe where no
    /// live worker can be attached (tests, edges added to parked rows).
    pub fn add_dependency_with_worker_reconcile(
        &self,
        input: AddDependencyInput,
    ) -> Result<(WorkItemDependency, Option<WorkExecution>)> {
        let relation = input
            .relation
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .unwrap_or(RELATION_BLOCKS);
        if relation != RELATION_BLOCKS {
            bail!("unsupported dependency relation `{relation}`; only `blocks` is implemented in v1");
        }
        let dependent_id = input.dependent.trim();
        let prerequisite_id = input.prerequisite.trim();
        if dependent_id.is_empty() || prerequisite_id.is_empty() {
            bail!("dependent and prerequisite ids are required");
        }

        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        let now = now_string();
        let (edge, reaped) = add_dependency_edge_in_tx(&tx, dependent_id, prerequisite_id, relation, &now)?;
        tx.commit()?;
        Ok((edge, reaped))
    }

    /// Drop the named edge if it exists. No-op success when the edge
    /// is already absent (mirrors `boss <kind> delete` on an
    /// already-archived row).
    pub fn remove_dependency(&self, input: RemoveDependencyInput) -> Result<bool> {
        let relation = input
            .relation
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .unwrap_or(RELATION_BLOCKS);
        let dependent_id = input.dependent.trim();
        let prerequisite_id = input.prerequisite.trim();
        if dependent_id.is_empty() || prerequisite_id.is_empty() {
            bail!("dependent and prerequisite ids are required");
        }
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        let removed = deps::delete_edge(&tx, dependent_id, prerequisite_id, relation)?;
        // Auto-unblock (Q4): when the only remaining gating reason is
        // gone and the engine itself put this row in `blocked` (identified
        // by blocked_reason='dependency'), flip it back to `todo`.
        // Human-placed blocks (other blocked_reason / NULL + human actor)
        // stick — the user must clear them.
        let now = now_string();
        maybe_engine_unblock_dependent(&tx, dependent_id, &now)?;
        tx.commit()?;
        Ok(removed)
    }

    /// All task ids that are currently in `blocked` status because of
    /// a dependency edge the engine set — i.e. rows that the periodic
    /// dependency-unblock sweeper should evaluate. Returns
    /// `(task_id, updated_at_epoch_secs)` so the sweeper can compute
    /// how long each row has been stuck.
    ///
    /// The candidate set is:
    ///   - `blocked_reason = 'dependency'`  — set by `maybe_engine_block_dependent`
    ///   - `blocked_reason IS NULL AND last_status_actor = 'engine'`  — pre-backfill rows
    pub fn list_dependency_blocked_candidates(&self) -> Result<Vec<(String, i64)>> {
        let conn = self.connect()?;
        let mut stmt = conn.prepare(
            "SELECT id, CAST(updated_at AS INTEGER)
             FROM tasks
             WHERE status = 'blocked'
               AND deleted_at IS NULL
               AND (
                   blocked_reason = 'dependency'
                   OR (blocked_reason IS NULL AND last_status_actor = 'engine')
               )
             ORDER BY updated_at ASC, id ASC",
        )?;
        let rows = stmt.query_map([], |row| Ok((row.get::<_, String>(0)?, row.get::<_, i64>(1)?)))?;
        let mut out = Vec::new();
        for row in rows {
            out.push(row?);
        }
        Ok(out)
    }

    /// Check whether `work_item_id` is still gated by unsatisfied
    /// prerequisites. If not — all prereqs are done and the block was
    /// engine-owned — flip the item to `todo` and return `true`.
    /// Returns `false` without modifying the DB when the item is not
    /// blocked, is human-blocked, or still has gating prereqs.
    ///
    /// Used by the periodic dependency-unblock sweeper as a per-item
    /// fallback for the case where the event-driven cascade
    /// ([`cascade_dependents_after_prereq_status_change`]) silently
    /// skipped this row (e.g. `last_status_actor` mismatch from a
    /// concurrent update, or engine was offline when the prereq landed).
    pub fn try_unblock_dependency_if_resolved(&self, work_item_id: &str) -> Result<bool> {
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        let now = now_string();
        let unblocked = maybe_engine_unblock_dependent(&tx, work_item_id, &now)?;
        tx.commit()?;
        Ok(unblocked)
    }

    /// Recovery sweep: find `todo, autostart=true` tasks whose latest execution
    /// is `waiting_dependency` (or absent) and whose gating prereqs are all
    /// satisfied, then promote those executions to `ready`. Returns the ids of
    /// tasks that were recovered.
    ///
    /// This handles tasks that got stuck after an auto-unblock (Part B
    /// recovery): the auto-unblock transitions `blocked` → `todo` and creates a
    /// `ready` execution atomically, but tasks unblocked before that fix landed
    /// may still have a stale `waiting_dependency` execution with no one to
    /// promote it.
    pub fn promote_todo_autostart_stuck_executions(&self) -> Result<Vec<String>> {
        let mut conn = self.connect()?;
        let tx = conn.transaction()?;
        let candidates: Vec<String> = {
            let mut stmt = tx.prepare(
                "SELECT id FROM tasks
                 WHERE status = 'todo' AND autostart = 1 AND deleted_at IS NULL
                 ORDER BY updated_at ASC, id ASC",
            )?;
            stmt.query_map([], |row| row.get::<_, String>(0))?
                .collect::<rusqlite::Result<Vec<_>>>()?
        };
        let mut promoted = Vec::new();
        for work_item_id in candidates {
            if !deps::gating_prereqs_for(&tx, &work_item_id)?.is_empty() {
                continue;
            }
            let needs_promotion = match query_latest_execution_for_work_item(&tx, &work_item_id)? {
                Some(exec) => exec.status == ExecutionStatus::WaitingDependency,
                None => true,
            };
            if !needs_promotion {
                continue;
            }
            let kind = execution_kind_for_work_item(&tx, &work_item_id)?;
            let mut result = ExecutionReconcileResult::default();
            reconcile_work_item_execution(&tx, &mut result, &work_item_id, kind, ExecutionStatus::Ready)?;
            if !result.created.is_empty() || !result.updated.is_empty() {
                tracing::info!(
                    work_item_id = %work_item_id,
                    "dep-unblock sweep: promoted stuck todo execution to ready",
                );
                promoted.push(work_item_id);
            }
        }
        tx.commit()?;
        Ok(promoted)
    }

    /// Return the prerequisites and/or dependents of a single work
    /// item. Empty lists when nothing matches; errors only when the
    /// work item id itself is unknown.
    pub fn list_dependencies(&self, input: ListDependenciesInput) -> Result<WorkItemDependencyView> {
        let work_item_id = input.work_item.trim();
        if work_item_id.is_empty() {
            bail!("work_item id is required");
        }
        let conn = self.connect()?;
        // Validate the work item exists by classifying its id and
        // looking it up. Surfaces a clear error rather than returning
        // an empty list for typos.
        let _ = product_id_for_work_item(&conn, work_item_id)?;

        let direction = input.direction.unwrap_or_default();
        let prerequisites = match direction {
            DependencyDirection::Dependents => Vec::new(),
            DependencyDirection::Prereqs | DependencyDirection::Both => {
                deps::prerequisites_of(&conn, work_item_id, None)?
            }
        };
        let dependents = match direction {
            DependencyDirection::Prereqs => Vec::new(),
            DependencyDirection::Dependents | DependencyDirection::Both => {
                deps::dependents_of(&conn, work_item_id, None)?
            }
        };
        Ok(WorkItemDependencyView {
            work_item_id: work_item_id.to_owned(),
            prerequisites,
            dependents,
        })
    }

    /// Resolved counterpart of [`Self::list_dependencies`]: each edge
    /// is collapsed into the peer's id + status + name + kind so the
    /// CLI / app shows the gate context without a second lookup.
    /// Drives the `boss <kind> show` Dependencies section (Q6).
    pub fn list_dependencies_detailed(&self, input: ListDependenciesInput) -> Result<WorkItemDependencyDetail> {
        let work_item_id = input.work_item.trim();
        if work_item_id.is_empty() {
            bail!("work_item id is required");
        }
        let conn = self.connect()?;
        let _ = product_id_for_work_item(&conn, work_item_id)?;

        let direction = input.direction.unwrap_or_default();
        let prerequisites = match direction {
            DependencyDirection::Dependents => Vec::new(),
            DependencyDirection::Prereqs | DependencyDirection::Both => {
                let edges = deps::prerequisites_of(&conn, work_item_id, None)?;
                edges
                    .into_iter()
                    .map(|edge| {
                        let peer_id = edge.prerequisite_id.clone();
                        resolve_dependency_edge(&conn, &peer_id, &edge.relation)
                    })
                    .collect::<Result<Vec<_>>>()?
            }
        };
        let dependents = match direction {
            DependencyDirection::Prereqs => Vec::new(),
            DependencyDirection::Dependents | DependencyDirection::Both => {
                let edges = deps::dependents_of(&conn, work_item_id, None)?;
                edges
                    .into_iter()
                    .map(|edge| {
                        let peer_id = edge.dependent_id.clone();
                        resolve_dependency_edge(&conn, &peer_id, &edge.relation)
                    })
                    .collect::<Result<Vec<_>>>()?
            }
        };
        Ok(WorkItemDependencyDetail {
            work_item_id: work_item_id.to_owned(),
            prerequisites,
            dependents,
        })
    }
}
