[package]
name = "boss-dispatch-events"
version.workspace = true
edition.workspace = true
workspace = "../../../.."

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bon = { workspace = true }
boss-engine-jsonl-append = { path = "../jsonl-append" }
boss-engine-utils = { path = "../utils" }
boss-log-files = { path = "../../log-files" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "sync"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
