//! Shared build-info stamping and `--version` handling for Boss binaries.
//!
//! Three Boss binaries — `boss` (cli), `bossctl`, and `boss-engine`
//! (engine/core) — each embed a Bazel-stamped base version and print it
//! for `--version` / `-V`. The stamping mechanism has one hard
//! constraint: the version constant is injected per-binary via
//! `include!(env!("BOSS_BUILD_INFO_RS"))`, and each `rust_binary` sets
//! its own `BOSS_BUILD_INFO_RS` in `rustc_env`. So the `include!` MUST
//! be evaluated inside each binary crate's own compilation — a plain
//! shared function that did the include once would bake in whichever
//! crate happened to compile this one.
//!
//! This crate factors out the two pieces that *can* be shared:
//!   - [`stamp!`] — a macro each binary invokes to generate its own
//!     `build_info` module (the per-crate `include!` plus a
//!     `version_string` accessor matching
//!     `boss_engine::build_info::version_string`).
//!   - [`print_version_if_requested`] — the `--version` / `-V` argv
//!     fast-path that all three `main()`s used to duplicate verbatim.
//!
//! The engine keeps its own richer `boss_engine::build_info` module
//! (binary fingerprint, mtime, process start time) — it only borrows
//! [`print_version_if_requested`] here. `boss` and `bossctl`, which
//! previously hand-rolled an identical stamp module plus version
//! helper, converge on [`stamp!`].

/// If the process was invoked with `--version` or `-V` as its first
/// argument, print `version` to stdout and return `true`; otherwise
/// return `false`.
///
/// Call this at the very top of `main()`, before argument parsing, and
/// return the caller's own success value when it returns `true`:
///
/// ```ignore
/// if boss_build_info::print_version_if_requested(&build_info::version_string("boss")) {
///     return std::process::ExitCode::SUCCESS;
/// }
/// ```
///
/// The engine, whose `main` returns `anyhow::Result<()>`, returns
/// `Ok(())` instead.
pub fn print_version_if_requested(version: &str) -> bool {
    if is_version_flag(std::env::args().nth(1).as_deref()) {
        println!("{version}");
        true
    } else {
        false
    }
}

/// Whether `first_arg` (argv[1]) is a version-request flag. Split out
/// from [`print_version_if_requested`] so the argv-matching logic is
/// unit-testable without mutating the process's real arguments.
fn is_version_flag(first_arg: Option<&str>) -> bool {
    matches!(first_arg, Some("--version") | Some("-V"))
}

/// Generate a private `build_info` module in the invoking binary crate,
/// stamping *that crate's* `BOSS_BUILD_INFO_RS`.
///
/// The `include!(env!("BOSS_BUILD_INFO_RS"))` deliberately lives in the
/// expansion — i.e. in the caller's compilation — because each
/// `rust_binary` sets its own `BOSS_BUILD_INFO_RS` (the Bazel-stamped
/// path in release builds, the checked-in default file in Cargo
/// builds). Doing the include once in this shared crate would bake in
/// the wrong path.
///
/// Expands to:
///
/// ```ignore
/// mod build_info {
///     pub fn version_string(binary_name: &str) -> String { /* ... */ }
/// }
/// ```
///
/// so the caller uses `build_info::version_string("boss")`, matching the
/// `boss_engine::build_info::version_string` interface.
#[macro_export]
macro_rules! stamp {
    () => {
        /// Per-binary build-info stamp, generated by
        /// [`boss_build_info::stamp!`].
        mod build_info {
            // Per-crate stamp: evaluated with this crate's rustc_env.
            // BOSS_GIT_SHA / BOSS_BUILD_TIME are part of the stamped
            // file's shape but unused here (the CLIs only surface the
            // version); they carry `#[allow(dead_code)]` at their
            // definition site so this include compiles clean.
            mod stamp {
                include!(env!("BOSS_BUILD_INFO_RS"));
            }

            /// Canonical `--version` string: `<binary_name> <version>`
            /// (e.g. `boss 1.0.4-dev-f3be785`). Mirrors
            /// `boss_engine::build_info::version_string`.
            pub fn version_string(binary_name: &str) -> String {
                format!("{binary_name} {}", stamp::BOSS_VERSION)
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::is_version_flag;

    #[test]
    fn recognizes_version_flags() {
        assert!(is_version_flag(Some("--version")));
        assert!(is_version_flag(Some("-V")));
    }

    #[test]
    fn rejects_non_version_flags() {
        assert!(!is_version_flag(None));
        assert!(!is_version_flag(Some("")));
        assert!(!is_version_flag(Some("-v")));
        assert!(!is_version_flag(Some("version")));
        assert!(!is_version_flag(Some("--help")));
        assert!(!is_version_flag(Some("task")));
    }
}
