"""Canonical Bazel identity for the engine executable."""

ENGINE_BINARY_PACKAGE = "tools/boss/engine/core"
ENGINE_BINARY_NAME = "engine"
ENGINE_BINARY_TARGET = "//%s:%s" % (ENGINE_BINARY_PACKAGE, ENGINE_BINARY_NAME)
ENGINE_BINARY_BAZEL_RELPATH = "bazel-bin/%s/%s" % (ENGINE_BINARY_PACKAGE, ENGINE_BINARY_NAME)
ENGINE_BINARY_BAZEL_RUN_COMMAND = "bazel run %s" % ENGINE_BINARY_TARGET
ENGINE_BINARY_BAZEL_OUTPUT_FRAGMENT = "/%s/%s" % (ENGINE_BINARY_PACKAGE, ENGINE_BINARY_NAME)
ENGINE_BINARY_BUNDLE_FRAGMENT = "Contents/Resources/bin/%s" % ENGINE_BINARY_NAME
